name: karteikarten_app
description: "Flashcards aus PDF (Frage/Antwort) – Flutter + Web"
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.1.2
  shared_preferences: ^2.2.3
  syncfusion_flutter_pdf: ^26.1.35
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.3
  file_selector: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
