// lib/services/builtin_h1_full.dart
import 'dart:convert';

import '../models/flashcard.dart';
import '../services/storage_service.dart';

/// Installiert das eingebaute H1-Deck (komplett) aus der TSV-Konstanten unten.
/// Nutzt den (web-tauglichen) StreamingDeckWriter aus StorageService.
Future<(int cards, int notes)> installH1FullDeck() async {
  final writer = await StreamingDeckWriter.begin(
    title: 'H1 Fachgespräch (eingebaut, komplett)',
    sourceName: 'H1-Fachgespräch (eingebaut)',
  );

  final lines = const LineSplitter().convert(_H1_TSV.trim());
  for (final raw in lines) {
    if (raw.trim().isEmpty || raw.startsWith('#')) continue;
    final parts = raw.split('\t');
    if (parts.length < 3) continue;

    final nr = parts[0].trim();
    final q  = parts[1].trim();
    final a  = parts.sublist(2).join('\t').trim();

    if (q.isEmpty || a.isEmpty) continue;

    final id = _fnv64Hex('$nr\n$q\n$a');
    writer.appendCards([Flashcard(id: id, number: nr, question: q, answer: a)]);
  }

  await writer.finish();
  return (writer.cardCount, writer.unmatchedCount);
}

String _fnv64Hex(String s) {
  final mask64 = BigInt.parse('0xFFFFFFFFFFFFFFFF');
  var hash = BigInt.parse('0xcbf29ce484222325');
  final prime = BigInt.parse('0x100000001b3');
  for (final b in utf8.encode(s)) {
    hash = (hash ^ BigInt.from(b)) & mask64;
    hash = (hash * prime) & mask64;
  }
  return hash.toRadixString(16).padLeft(16, '0');
}

// ———————————————————————————————————————————————————————————————
// TSV-Daten: "Nr.\tFrage\tAntwort"
// (du hattest diesen Block gepostet; ich lasse ihn hier 1:1 drin)
// ———————————————————————————————————————————————————————————————
const String _H1_TSV = r'''Nr. 0001	Welches sind die drei wichtigsten Größen in der Elektrotechnik? 	 Elektrische Spannung (U - Volt) Elektrische Stromstärke (l - Ampere) Elektrischer Widerstand (R - Ohm)
Nr. 0002	Wie lässt sich die Spannung erklären? 	Die elektrische Spannung U ist der Unterschied in der Elektronenbesetzung zwischen zwei Punkten.  Minuspol = Elektronen Überschuss Pluspol = Elektronen Mangel  Spannung entsteht durch Ladungstrennung. Das Ausgleichsbestreben getrennter Ladung ist die elektrische Spannung U
Nr. 0003	Was ist Strom und welche Wirkung hat er? 	 Unter Strom (I) versteht man das Fließen von freien Elektronen Fließrichtung vom Minuspol zum Pluspol (Wirkliche Stromrichtung)  Die verschiedenen Wirkungen des elektrischen Stromes sind:  Wärmewirkung (Bügeleisen, Tauchsieder, Lötkolben) Lichtwirkung (Glühlampen, LED, Leuchtstoﬀröhre) Magnetische Wirkung (Elektromagnete, Elektromotoren, Lautsprecher) Chemische Wirkung (Elektrolyse, Galvanisieren, Akkumulatoren) Wirkung auf Lebewesen (physiologische Wirkung) (Elektroweidezäune,Elektromedizinische Geräte)  Stand: 01.12.2021  Seite 3 / 98  Stand: 01.12.2021  Seite 4 / 98  Fachkunde Elektrotechnik, 24. Auﬂage, Verlag Europa Lehrmittel
Nr. 0004	Was besagt das Ohmsche Gesetz? 	Die Größe vom Strom ist von der Größe des Widerstandes des Verbrauchers und der Größe angelegten Spannung abhängig (elektrischer Stromkreis).  Der Zusammenhang zwischen Spannung, Strom und dem elektrischen Widerstand in einem geschlossenen Stromkreis beschreibt das Ohmsche Gesetz.  U = R × I
Nr. 0005	Welche Stromarten werden unterschieden und wo werden sie angewendet? 	Gleichstrom (DC): ﬂießt stets in gleicher Richtung (z.B. Galvanotechnik, Lichtbogenschweißen, Gleichstrommotoren,...)  Wechselstrom (AC): ist ein Strom, der periodisch seine Richtung und Stärke ändert (z.B. Energienetz, Schweißtechnik)  Dreiphasen-Wechselstrom (Drehstrom): sind 3 Wechselströme, die zeitlich um 120° versetzt sind (z.B. CEEKraftsteckdose, für große Verbraucher, Drehstrommotoren)  Mischstrom (UC): setzt sich aus einem Wechselstromanteil und einen Gleichstrimanteil zusammen  Stand: 01.12.2021  Seite 5 / 98  Fachkunde Elektrotechnik, 24. Auﬂage, Verlag Europa Lehrmittel
Nr. 0006	Ab welcher Stromstärke besteht für den Menschen Lebensgefahr? 	ab 50mA!  Erklärung I = U / R   = 50Volt / 1000 Ohm (Widerstand des Menschen)   = 0,05 Ampere = 50 mA  Stand: 01.12.2021  Seite 6 / 98  Fachkunde Elektrotechnik, 24. Auﬂage, Verlag Europa Lehrmittel
Nr. 0007	Welche elektrischen Gefahren können für Personen an Maschinen auftreten? 	Bei defekten elektrischen Teilen (z.B. beschädigte Kabel, defekte Gehäuse von Geräten) kann die Person durch Berührung eine zu hohe Spannung geraten und dadurch einen elektrischen Stromschlag bekommen.
Nr. 0008	Wie wirkt der Strom auf den Menschen? 	 Verbrennung Herzrhythmusstörung Verkrampfung Blutzersetzung (Vergiftung) Tod
Nr. 0009	Was ist bei einem elektrischen Unfall zu unternehmen?  Stand: 01.12.2021  Seite 7 / 98  	-Den Stromkreis unterbrechen bzw. abschalten (FI - Schutzschalter, Sicherung oder Leitungsschalter) -Aus dem Gefahrenbereich bringen -Funktion der Organe kontrollieren, wenn nötig Wiederbelebungsversuche durchführen -Arzt verständigen / Krankenhaus aufsuchen
Nr. 0010	Worauf muss beim Anschluss des Schutzleiters in einem Stecker (Schuko-Stecker, CEE-Stecker, ...) besonders geachtet werden? 	Der Schutzleiter muss immer etwas länger sein als die anderen Leiter, damit beim Ausreißen des Kabels die Verbindung des Schutzleiters als letztes ausreißt.
Nr. 0011	Worauf ist bei der Verwendung von Kabeltrommeln bei größerer Dauerleistung (Verbraucher ab ca. 500W) zu achten? 	Das Kabel muss ganz von der Trommel abgerollt werden, da sich das Kabel erwärmt und die Wärme ansonsten vom Inneren der Trommel nicht an die Umgebung abgegeben werden kann.
Nr. 0012	In welchem Betriebszustand werden Schalter und Geräte in einem Stromlaufplan gezeichnet? 	Im stromlosen und nicht betätigten Zustand. (Ausnahme: bei mechanischer Betätigung)
Nr. 0013	Wie funktioniert ein Relais?  8068.29080 	Relais sind elektromagnetische Schalter. D.h. es ﬂießt ein Strom durch eine Spule. Dadurch wird ein Magnetfeld erzeugt. Durch das Magnetfeld wird ein Anker angezogen, der über eine mechanische Verbindung einen oder mehrere Kontakte schaltet.  Stand: 01.12.2021  Seite 8 / 98  Fachkunde Elektrotechnik, 24. Auﬂage, Verlag Europa Lehrmittel
Nr. 0014	Welche pneumatischen Komponenten werden in ihrem Betrieb eingesetzt? 	Betriebsspeziﬁsche Antwort über Drucklufterzeugung bis zu den verwendeten Komponenten im Anlagenbau oder der Produktion
Nr. 0015	Welche Vorzüge hat die Pneumatik? 	 Kräfte und Geschwindigkeiten der Zylinder sind stufenlos einstellbar Zylinder und Druckluftmotoren erreichen hohe Geschwindigkeiten und Drehzahlen Druckluftgeräte können ohne Schaden bis zum Stillstand überlastet werden Druckluft ist in Druckbehältern speicherbar Druckluft ist sauber, daher keine Verschmutzungen Preiswerte Steuer- und Arbeitselemente
Nr. 0016	Welche Nachteile hat die Pneumatik? 	 Die Kolbenkräfte sind begrenzt aufgrund der geringen Arbeitsdrücke Gleichmäßige und konstante Kolbengeschwindigkeiten ist so gut wie nicht möglich (Komprimierbarkeit der Luft) Genaue Endlagen sind nur mit Festanschlägen möglich (Ausnahme Servopneumatische Achse ==> Proportional-Wegeventil mit Wegmesssystem) Erzeugung & Aufbereitung von Druckluft ist teuer Als Steuermedium langsam  Stand: 01.12.2021  Seite 9 / 98
Nr. 0017	Aus welchen Hauptgruppen besteht eine pneumatische Steuerung? 	 Arbeitsteil (Zylinder) Steuerteil (Ventile) Energieteil (Druckluftversorgung und Aufbereitung)  Stand: 01.12.2021  Seite 10 / 98  Fachkunde Metall, 57. Auﬂage, Verlag Europa Lehrmittel
Nr. 0018	Welche Komponenten beinhaltet eine Verdichteranlage? 	 Antriebsmotor Ansaugﬁlter Verdichter Lufttrockner Druckluftspeicher mit Kondensationsabscheider Wartungseinheit mit (Druckluftﬁlter mit Wasserabscheider, Druckreglelventil, bei Bedarf auch mit Öler)
Nr. 0019	Welche Arten von Verdichtern werden überwiegend eingesetzt? 	 Hubkolbenverdichter Membranverdichter Schraubenverdichter Flügelzellenverdichter  Fachkunde Metall, 57. Auﬂage, Verlag Europa Lehrmittel
Nr. 0020	Welche Verfahren der Lufttrocknung werden angewendet?  Stand: 01.12.2021  Seite 12 / 98  	 Adsorptionstrocknung (Trocknungsmittel-Siliziumdioxid) Absorptionstrocknung (chemisches Verfahren) Kältetrocknung (Wärmetauscher und Kälteaggregat)
Nr. 0021	Woraus besteht die Aufbereitungseinheit (Wartungseinheit)? 	Die Aufbereitungseinheit ist eine Gerätekombination von  Druckluftﬁlter mit Wasserabscheider Druckregelventil bei Bedarf auch noch zusätzlich mit Öler 3/2 Wegeventil (Absperrhahn)  Fachkunde Metall, 57. Auﬂage, Verlag Europa Lehrmittel
Nr. 0022	Welche Arbeitselemente werden in der Pneumatik eingesetzt? 	 Zylinder mit linearer Bewegung (Kolbenstangenzylinder [einfachwirkende, doppelwirkend], Kurzhubzylinder, kolbenstangenlose Zylinder..) Zylinder mit drehender Bewegung (Drehzylinder u. Drehﬂügelzylinder) Druckluftmotoren für Schrauber, Handschleifgeräte, Hebezeuge (Lamellen, Kolben oder Zahnradmotor)  Pneumatische Arbeitselemente wandeln die in der Druckluft gespeicherte und durch die Druckluft übertragene Energie in mechanische Arbeit um.  Stand: 01.12.2021  Seite 13 / 98  Fachkunde Metall, 57. Auﬂage, Verlag Europa Lehrmittel  Fachkunde Metall, 57. Auﬂage, Verlag Europa Lehrmittel  Fachkunde Metall, 57. Auﬂage, Verlag Europa Lehrmittel  Stand: 01.12.2021  Seite 14 / 98
Nr. 0023	Welchen Zweck hat die Endlagendämpfung eines Pneumatikzylinders? 	Sie verringert die Kolbengeschwindigkeit, sodass der Kolben sanft in seine Endlage fährt.
Nr. 0024	Welchen Vorteil bieten kolbenstangenlose Zylinder? 	 Sie benötigen weniger Platz, als Zylinder mit Kolbenstangen. Kolbenkraft für Vor- und Rückhub  sind idetentisch.  Fachkunde Metall, 57. Auﬂage, Verlag Europa Lehrmittel
Nr. 0025	Wovon hängt die wirksame Kolbenkraft bei Zylindern ab? 	Die wirksame Kolbenkraft ist abhängig von der Kolbenﬂäche, dem Druck und dem Wirkungsgrad.  Fachkunde Metall, 57. Auﬂage, Verlag Europa Lehrmittel  Stand: 01.12.2021  Seite 15 / 98  Fachkunde Metall, 57. Auﬂage, Verlag Europa Lehrmittel
Nr. 0026	In welche Hauptgruppen können Steuerventile unterteilt werden? 	 Wegeventile (3/2, 4/2 WV ...) Sperrventile (Zweidruck-, Wechsel-, Rückschlagventile) Druckventile (Druckbegrenzungs- und Druckregelventile) Stromventile (Drossel- und Drosselrückschlagventile)
Nr. 0027	Was bedeutet die Bezeichnung „5/3-Wegeventil“? 	Das 5/3-Wegeventil ist ein Wegeventil mit 5 gesteuerten Anschlüssen und 3 Schaltstellungen. Die Mittelstellung ist zugleich die Nullstellung des Ventils.  Fachkunde Metall, 57. Auﬂage, Verlag Europa Lehrmittel
Nr. 0028	Welche Wegeventile werden zum Steuern von Zylindern eingesetzt? 	 Einfachwirkende Zylinder werden meist mit 3/2-Wegeventilen angesteuert Doppeltwirkende mit 4/2-, 5/2- oder 5/3-Wegeventilen angesteuert
Nr. 0029	Welche Betätigungsarten von Wegeventilen gibt es? 	Die Betätigung der Wegeventile erfolgt:  manuell mechanisch pneumatisch elektrisch elektropneumatisch  Fachkunde Metall, 57. Auﬂage, Verlag Europa Lehrmittel
Nr. 0030	Wie kann die Kolbengeschwindigkeit reguliert werden? 	 Drosselventile Drosselrückschlagventile (Zu- oder Abluftdrosselung) Schnellentlüftungsventile  Stand: 01.12.2021  Seite 17 / 98  Fachkunde Metall, 57. Auﬂage, Verlag Europa Lehrmittel  Fachkunde Metall, 57. Auﬂage, Verlag Europa Lehrmittel
Nr. 0031	Warum wird in den meisten Fällen die Abluftdrosselung bevorzugt? 	Durch den Strömungswiderstand des Drosselrückschlagventils baut sich ein Gegendruck auf. Der Kolben wird „eingespannt“. Dadurch ergibt sich eine gleichmäßige Kolbenbewegung (Vermeiden vom Stick-Slip-Eﬀekt) und der Kolben kann bei Zuglast nicht ausgezogen werden.
Nr. 0032	Welche Signalverknüpfungen sind mit Zweidruck- und mit Wechselventilen möglich? 	Zweidruckventile ergeben die logische Funktion UND. Am Ventilausgang liegt nur dann Druck an, wenn beim Zweidruckventil Eingang E1 UND E2 beaufschlagt werden.  Wechselventile ergeben die logische Funktion ODER. Am Ventilausgang liegt dann Druck an, wenn beim Wechselventil E1 ODER E2 beaufschlagt werden.  Fachkunde Metall, 57. Auﬂage, Verlag Europa Lehrmittel  Stand: 01.12.2021  Seite 18 / 98  Fachkunde Metall, 57. Auﬂage, Verlag Europa Lehrmittel
Nr. 0033	Welche Aufgaben haben Druckbegrenzungsventile und Druckregelventile? 	 Druckbegrenzungsventile (Überduckventile kurz DBV) sichern Behälter, Leitungen und Bauelemente gegen Überdruck. Druckregelventile (Druckminderventile) regeln den schwankenden Betriebsdruck auf einen konstanten Arbeitsdruck.  Fachkunde Metall, 57. Auﬂage, Verlag Europa Lehrmittel  Stand: 01.12.2021  Seite 19 / 98  Fachkunde Metall, 57. Auﬂage, Verlag Europa Lehrmittel
Nr. 0034	Was kann zu Störungen in der Pneumatik führen? 	 Leckage Falsche Montage (z.B. falsche Drosselung, Leitungsknicke, undichte Verschraubungen, ...) Verschmutzte Druckluft Zu wenig Druck Undichte Manschetten bei Druckluftzylindern Innere Undichtheit bei Steuerungsventile
Nr. 0035	Welche elektropneumatischen Komponenten werden in ihrem Betrieb eingesetzt? 	Betriebsspeziﬁsche Antwort über die verwendeten Komponenten im Anlagenbau oder Produktion<!--Break-->
Nr. 0036	Welche hydraulischen Komponenten werden in ihrem Betrieb eingesetzt? 	Betriebsspeziﬁsche Antwort über die sich im Einsatz beﬁndenden Hydraulikaggregate und verwendete Komponenten im Anlagenbau oder den Produktionsanlagen<!--Break-->
Nr. 0037	Welche Vorzüge bietet die Hydraulik gegenüber der Pneumatik und Elektrik?  Stand: 01.12.2021  Seite 20 / 98  	 Übertragung großer Kräfte bei Einsatz kleiner Aktoren Exaktes Positionieren ohne Fixanschläge Gleichmäßige, lastenunabhängige Bewegung, da Flüssigkeiten kaum komprimierbar sind und Regelventile eingesetzt werden können Weiches Arbeiten und Umschalten
Nr. 0038	Welches sind die wichtigsten zwei Kenngrößen in der Hydraulik und was bewirken sie? 	Der Druck - p (bar): Bewirkt die Kolbenkraft eines Zylinders Der Volumenstrom - Q (l/min): Bewirkt die Kolbengeschwindigkeit eines Zylinders
Nr. 0039	Wie gliedert sich der Aufbau einer hydraulischen Anlage? 	 Arbeitsteil (Zylinder) Steuerteil (Wegeventile) Energieteil (Hydraulisches Aggregat mit Behälter, Filter, Pumpe, Motor, DBV) Druckleitungen  Fachkunde Metall, 57. Auﬂage, Verlag Europa Lehrmittel
Nr. 0040	Aus welchen wichtigsten Bestandteilen setzt sich das Hydraulik - Aggregat zusammen? 	 Stand: 01.12.2021  Seite 21 / 98  Behälter (Tank) Antrieb (Motor) Pumpe Filter Druckbegrenzungsventil (DBV)
Nr. 0041	Welches sind die wichtigsten Kenndaten einer Pumpe? 	Verdrängungsvolumen (V): Es bezeichnet das Flüssigkeitsvolumen, das von der Pumpe pro Umdrehung (bzw. pro Hub) gefördert wird.  Betriebsdruck (p): Es wird der Spitzendruck angegeben, dieser sollte aber nur kurzzeitig auftreten (Pumpenverschleiß).  Drehzahl (n)  Der Förderstrom (Q) einer Pumpe ist von der Drehzahl abhängig. Viele Pumpen sind nur für einen bestimmten Drehzahlbereich freigegeben.  Wirkungsgrad (eta) Der Wirkungsgrad ist abhängig vom Konstruktionsprinzip, der Betriebsdauer (Verschleiß) und verschiedenen Betriebsparametern, wie z.B. Druck, Drehzahl und Viskosität.
Nr. 0042	Welche Pumpen zählen zu den Konstantpumpen? 	 Außenzahnradpumpen Innenzahnradpumpen Schraubenspindelpumpen Flügelzellenpumpe (kann auch als Verstellpumpe ausgeführt werden)  Konstantpumpen nennt man Pumpen mit nicht verstellbarem Verdrängungsvolumen - V (cm³ pro 1 Umdr).  Fachkunde Metall, 57. Auﬂage, Verlag Europa Lehrmittel  Stand: 01.12.2021  Seite 22 / 98  Fachkunde Metall, 57. Auﬂage, Verlag Europa Lehrmittel
Nr. 0043	Welche Arten von Verstellpumpen gibt es? 	 Flügelzellenpumpe Axialkolbenpumpe Radialkolbenpumpe  Fachkunde Metall, 57. Auﬂage, Verlag Europa Lehrmittel  Stand: 01.12.2021  Seite 23 / 98  Fachkunde Metall, 57. Auﬂage, Verlag Europa Lehrmittel
Nr. 0044	Welchen Vorteil bieten Verstell- und Regelpumpen? 	Bei der Verstellpumpe kann das Verdrängungsvolumen bzw. der Volumenstrom, je nach Bedarf, eingestellt werden. Bei der Regelpumpe ändert sich das Verdrängungsvolumen bzw. der Volumenstrom, je nach Anforderung, ständig.
Nr. 0045	Auf welche Weise wird bei einer Radialkolbenpumpe der Volumenstrom verstellt? 	Durch verstellen des Hubringes (Exzentermaß), wird der Kolbenhub (Null bis Maximum) verändert.
Nr. 0046	Welches Element dient zum Schutz einer Hydraulikanlage vor Überdruck? 	Das Druckbegrenzungsventil (DBV).  Fachkunde Metall, 57. Auﬂage, Verlag Europa Lehrmittel
Nr. 0047	Wie kann die Kolbengeschwindigkeit reguliert werden? 	 Durch Blenden lastabhängig Durch Drosseln lastabhängig Durch Stromregelventile lastunabhängig (auch bei Lastwechsel konstant) Durch Servo- bzw. Proportionalventile gesteuert und geregelt möglich  Fachkunde Metall, 57. Auﬂage, Verlag Europa Lehrmittel  Fachkunde Metall, 57. Auﬂage, Verlag Europa Lehrmittel
Nr. 0048	Welche Anforderungen werden an Hydraulikﬂüssigkeiten gestellt? 	Hydraulikﬂüssigkeiten müssen möglichst schmierfähig und alterungsbeständig sein. Ihre Viskosität soll mit der Temperatur möglichst wenig verändern. Bei höheren Arbeitstemperaturen, über 300 Grad, müssen sie schwer entﬂammbar sein.  Unterscheidung der Flüssigkeiten:  entﬂammbare (Mineralöle) schwer entﬂammbare Flüssigkeiten (Wasseremulsionen, Wasserglykollösungen) biologisch abbaubare Flüssigkeiten  Stand: 01.12.2021  Seite 25 / 98  Fachkunde Metall, 57. Auﬂage, Verlag Europa Lehrmittel
Nr. 0049	Was bewirken zu kleine Leitungsquerschnitte in einer Hydraulikanlage und welche Folgen können daraus entstehen? 	Ein zu hoher Volumensstrom (Strömungsgeschwindigkeit) hat eine turbulente Strömung zur Folge:  überhöhte Erwärmung der Flüssigkeit Zerstörung der Elemente an Verengungen durch Kavitation  (Dieseleﬀekt)  Fachkunde Metall, 57. Auﬂage, Verlag Europa Lehrmittel  Fachkunde Metall, 57. Auﬂage, Verlag Europa Lehrmittel  Stand: 01.12.2021  Seite 26 / 98
Nr. 0050	Was bewirkt eine zu starke Erwärmung des Hydrauliköles? 	Die Viskosität nimmt ab (dünnﬂüssig) und führt zu  Druckverlust Undichtheit Leckage Verschleiß tritt auf  Das Öl altert schneller
Nr. 0051	Was bedeutet die Bezeichnung "HLP 68" eines Hydrauliköles? 	H: Hydrauliköl auf Mineralölbasis L: erhöhte Korrosions- und Alterungsbeständigkeit P: erhöhten Verschleißschutz 68: Viskositätskennzahl (68mm²/s bzw. 68 centi Stoke)  8068.29138
Nr. 0052	Wo liegen die Viskositätsgrenzen? 	Untere Grenze 10mm²/s bzw. c St (centi Stoke) Durch überhöhte Erwärmung des Hydrauliköles wird es zu dünnﬂüssig, es treten Undichtheit, Leckage und Verschleiß auf.  Obere Grenze 100mm²/s bzw. c St Durch zu niedrige Umgebungstemperaturen wird das Hydrauliköl zu zähﬂüssig, es hat erhöhte Reibung zur Folge, der Kaltstart und das Abscheiden von Luftblasen wird erschwert (Kavitationsgefahr).  Stand: 01.12.2021  Seite 27 / 98  Fachkunde Metall, 57. Auﬂage, Verlag Europa Lehrmittel
Nr. 0053	Welche Aufgaben erfüllen Filter? 	Die Verschmutzung auf ein zulässiges Maß bzgl. Größe und Konzentration zu reduzieren (Lebensdauer der Bauelemente).  Die Auswahl und Anordnung des Filters richtet sich hauptsächlich nach der Schmutzempﬁndlichkeit der verwendeten Hydraulikkomponenten.
Nr. 0054	Wie kann die Anordnung der Filter erfolgen? 	Hauptstromﬁlterung:  Saugﬁlter Druckﬁlter Rücklauﬃlter  Nebenstromﬁlterung:  Druckﬁlter
Nr. 0055	Welche Aufgaben erfüllen Hydrospeicher? 	 8068.29143  Einsparung von Pumpen- und Antriebsleistung (Taktzeitoptimierung) - Abgabe zusätzlicher Druckﬂüssigkeit bei Eilbewegungen Energiereserve für Notfälle, z.B. bei Ausfall der Hydropumpe Stoß- und Schwingungsdämpfung Ausgleich von Leckverlusten Dämpfung von Schwingungen und Druckstößen Speichern von Druckﬂüssigkeiten solagen die Zylinder und Hydromotoren nicht arbeiten
Nr. 0056	Was soll bei einer Inbetriebnahme einer Hydraulikanlage beachtet werden? 	Durchführung nur von geschultem Fachpersonal. Dabei ist sind folgende Punkte zu berücksichtigen:  Füllstandskontrolle am Tank Kupplungen und Verschraubungen auf festen Sitz kontrollieren Druckbegrenzungsventile zurückdrehen  Stand: 01.12.2021  Seite 28 / 98  Drehrichtung des Motors (Pumpe) kontrollieren Tippweiser Start der Anlage, dabei auf Pumpengeräusche (Kavitation) achten Personen während der Inbetriebnahme fernhalten Anlage auf Dichtheit kontrollieren
Nr. 0057	Welche Aufgaben haben Grenztaster (Endschalter)? 	Ein Grenztaster ist ein Schalter der mechanisch betätigt wird. Sie haben die Aufgabe z.B. Bewegungen, Positionen oder Füllstände abzufragen und der Steuerung zu melden.
Nr. 0058	Welche Sensoren werden in der Elektropneumatik eingesetzt? 	Mechanische Taster und Schalter  Berührungslose Schalter  magnetisch betätigte Näherungsschalter (Reedkontakt) induktive Näherungsschalter induktive, kapazitive und optoelektronische Näherungsschalter
Nr. 0059	Wie ist die Funktionsweise von magnetisch betätigten Näherungsschaltern (Reedschalter)? 	Reedschalter schalten ohne mechanische Berührung. In einem Kunstharzblock sind zwei Kontakte mit einem schutzgasgefüllten Glasröhrchen eingeschmolzen. Durch Annähern eines Kolbens mit einem Permanentmagnet ziehen sich die überlappten Kontaktzungen sprungartig an und schalten. Durch das Entfernen des Magneten lösen sich die Kontaktzungen.  Fachkunde Metall, 57. Auﬂage, Verlag Europa Lehrmittel  Thema: Werkstoﬀtechnik
Nr. 0060	Was ist Stahl? 	Als Stahl bezeichnet man alle Eisenwerkstoﬀe, die für die Warmformgebung geeignet sind und nicht mehr als 2,06% C enthalten.  Durch unterschiedliche Herstellungen, Legierungen und Wärmebehandlungen, werden verschiedene und dem Verwendungszweck angepasste Stähle gefertigt.
Nr. 0061	Welches ist das meist verwendete Frischverfahren? 	Die meist verwendete Art ist das LD (Linz – Donawitz) – Verfahren, bei dem Sauerstoﬀ mit 8 – 12 bar durch die ﬂüssige Schmelze geblasen wird.  Es werden beim Frischen die unerwünschten Bestandteile (z.B. Schwefel , Phosphor usw.) fast völlig verbrannt, dabei wird auch der Kohlenstoﬀgehalt gesenkt.
Nr. 0062	Wodurch erhält der Stahl die gewünschten Eigenschaften? 	Die Eigenschaften der Stähle hängen weitgehend von den Legierungselementen und den erwünschten oder unerwünschten Begleitelementen ab.  Metallische Legierungsbestandteile sind: AL, Cr, Co, Mn, Mo, Ni, V, W  Nichtmetallische Begleitelemente sind: Kohlenstoﬀ, Wasserstoﬀ, Stickstoﬀ, Phosphor, Schwefel, Silizium
Nr. 0063	Wodurch unterscheiden sich nieder- bzw. hochlegierte Stähle? 	Bei niederlegierten Stählen liegt die Summe der Legierungsanteile unter 5%.  Hochlegierte Stähle haben mindestens ein Legierungselement mit mehr als 5% Anteil.
Nr. 0064	Wie sind die Stähle nach ihrer Verwendung unterteilt? 	 Stand: 01.12.2021  Seite 30 / 98
Nr. 0065	Wie unterscheiden sich die Baustähle von den Werkzeugstählen vom C-Gehalt? 	Baustähle ca. 0,05 - 0,6% C-Gehalt Werkzeugstähle ca. 0,6 - 2,2% C-Gehalt
Nr. 0066	Welche Voraussetzung benötigt ein härtbarer Stahl? 	Nur Stähle mit mehr als 0,2% Kohlenstoﬀ sind zum Härten geeignet.
Nr. 0067	Wo wird Stahlguss verwendet? 	-Hochbelastete Werkstücke -Großmaschinenbau -Pressenständer -Radsätze -Kleinteile für Armaturen -Land- und Werkzeugmaschinen - kann auch legiert werden  8068.29200
Nr. 0068	Welche Vorteile bringt die Herstellung von Werkstücken durch Gießen? 	Es können komplizierte Werkstückformen wirtschaftlich hergestellt werden.
Nr. 0069	Was sagen Werkstoﬀnummern aus?  Stand: 01.12.2021  Seite 31 / 98  	[keine Antwort im Text gefunden]
Nr. 0070	Wie werden Nichteisenmetalle ein- bzw. unterteilt? 	-Schwermetalle: Kupfer, Nickel, Zink, Blei, Zinn und deren Legierungen; 5 kg / dm3 -Legierungsmetalle: Wolfram, Chrom, Molybdän, Vanadium, Cobalt, Mangan -Leichtmetalle: AL + Legierungen, Magnesiumlegierungen, Titan; 5kg/dm3
Nr. 0071	Welches sind die häuﬁgsten Legierungen von Nichteisenmetallen? 	Kupfer-Zink = Messing Kupfer-Zinn = Bronze Kupfer- Blei-Zinn = Lagermetalle Aluminium- Magnesium = Niedrigfeste Legierung Aluminium-Zinn-Magnesium-Kupfer = Hochfeste Legierung
Nr. 0072	Welche Eigenschaften hat Kupfer (Cu)? 	-Weich und gut dehnbar -Elektrische und Wärmeleitfähigkeit -Korrosionsbeständigkeit -An der Luft bildet sich Edelrost (Patina) -Kupfer ist gut walz-, verform- und gießbar sowie schweiß- und legierbar
Nr. 0073	Wofür werden Kupferlegierungen verwendet? 	Kupfer, Zink = Armaturen-, Uhrenfeinmechanik Kupfer, Zinn = Muttern, Schneckenräder, Gleitlager Kupfer, Zinn, Zink = Muttern, Schneckenräder, Gleitlager Kupfer, Blei, Zinn = Lagermetalle, sehr gute Gleit- und Notlaufeigenschaft  Stand: 01.12.2021  Seite 32 / 98
Nr. 0074	Wie werden die Kunststoﬀe in Hauptgruppen eingeteilt? 	Thermoplaste: warm umformbar und schweißbar Duroplaste: nicht umformbar nicht schweißbar Elastomere: gummielastisch nicht verformbar und nicht schweißbar
Nr. 0075	Was für Eigenschaften haben Kunststoﬀe? 	-Geringe Dichte -Verschiedene mechanische Eigenschaften -Elektrisch isolierend -Wärmedämmend -Korrosionsbeständig -Gut umformbar und bearbeitbar -Einfärbbar -Glatte dekorative Oberﬂäche
Nr. 0076	Welche Eigenschaften haben Verbundwerkstoﬀe? 	Es können mehrere Eigenschaften von verschiedenen Materialien verbunden werden. Schlechte Eigenschaften werden überdeckt und mit verschiedenen Materialien können die Eigenschaften hochwertiger Werkstoﬀe erzielt werden.
Nr. 0077	Wo werden Verbundwerkstoﬀe verwendet? 	-Fahrzeug- und Maschinenbau -Zahnräder -Spezialwerkzeuge -Karosserie- und Flugzeugbau -Rohrleitungen -Behälter -Sportgeräte -Wendeschneidplatten
Nr. 0078	Was sagt der Begriﬀ „Sintern“ aus?  8068.29288  Stand: 01.12.2021  Seite 33 / 98  	Gesinterte Werkstoﬀe werden aus Metallpulver hergestellt, welches durch hohen Druck zu Werkstückpresslingen geformt wird. Diese Presslinge erhalten durch eine anschließende Wärmebehandlung dem „Sintern“ ihre Endfestigkeit. Die Technik des „Sinterns“ bezeichnet man auch als Pulvermetallurgie.
Nr. 0079	Wie erfolgt die Herstellung von gesinterten Werkstoﬀen? 	Die Herstellung erfolgt in mehreren Stufen: Pulverherstellung, Pressen des Pulvers zu Formteilen, Sintern der Presslinge, Nachpressen und Kalibrieren.  Die Sinterzeit beträgt je nach Größe des Werkstückes zwischen 30 – 150 min.  Die Sintertemperatur reicht von 600° - 3200°C.Beispiele für gesintertes Material sind:Hartmetall Metallkeramik Kupfer-Graﬁt-Legierung
Nr. 0080	Wie werden Hilfsstoﬀe eingeteilt? 	-Kühlschmierstoﬀe -Reinigungsmittel -Löthilfsmittel -Schmierstoﬀe -Druckluft -elektr. Strom
Nr. 0081	Was muss beim Einsatz von Kühlschmierstoﬀen beachtet werden? 	-Regelmäßige Geruchs- und Sichtkontrolle -Regelmäßig PH-Wert und Ölgehalt prüfen -Sie sollen regelmäßig gereinigt oder erneuert werden  8068.29305
Nr. 0082	Was für Eigenschaften sollten Schmierstoﬀe (Fette, Öle, ...) besitzen? 	-Druckfest -Säure und Wasserfrei -Geringe Viskositätsänderung -Hoher Brennpunkt -Haftfähig -Geringe innere Reibung  Stand: 01.12.2021  Seite 34 / 98
Nr. 0083	Welche Aufgaben haben Schmierstoﬀe? 	-Verminderung der Reibung -Dämpfung von Stößen -Korrosionsschutz -Wärmeabfuhr -Abfuhr von Verschleißteilchen
Nr. 0084	Was ist Glühen?  8068.29335 	Glühen ist eine Wärmebehandlung, bestehend aus langsamen Erwärmen, Halten auf Glühtemperatur und langsamen Abkühlen. Mit Glühen können bleibende Gefügeveränderungen erreicht werden.
Nr. 0085	Wodurch unterscheidet sich das Glühen vom Härten? 	Glühen und Härten unterscheiden sich durch die Höhe der Temperatur und die Art der Abkühlung. Beim Glühen wird langsam abgekühlt, beim Härten wird abgeschreckt.
Nr. 0086	Warum und wie wird weichgeglüht? 	Beim Weichglühen erwärmt man den Stahl je nach Kohlenstoﬀgehalt auf 680°C bis 750°C und hält ihn dort mehrere Stunden. Durch das Weichglühen wandelt sich der Streifenzementit in körnigen Zementit um. Dadurch ist der Werkstoﬀ leichter umformbar und spanbar. Auch gehärtete Werkstücke können durch Weichglühen wieder spanbar gemacht werden.
Nr. 0087	Warum wird das Spannungsarmglühen angewendet? 	Beim Spannungsarmglühen werden innere Spannungen im Werkstück durch plastisches Fließen des Werkstoﬀs bei Glühtemperatur verringert.  Die inneren Spannungen können durch Gießen, Walzen, Schmieden oder Schweißen und mechanischen Bearbeitungen (Drehen, Fräsen, Kaltumformen, Tiefziehen usw.) entstanden sein.  Das Glühen der Werkstücke erfolgt bei 550°C bis 650°C während 1 bis 4 Stunden.  Stand: 01.12.2021  Seite 35 / 98  8068.29353
Nr. 0088	Was gibt es für Glühverfahren? 	-Spannungsarmglühen 550°C bis 650°C -Rekristallisationsglühen 550°C bis 650°C -Weichglühen 680°C bis 750°C -Normalglühen knapp oberhalb der GSK-Linie -Diﬀusionsglühen 1050°C bis 1250°C  Temperaturen gelten nur für unlegierte Stähle!
Nr. 0089	Was wird durch Vergüten erreicht? 	Vergüten ist eine Standard-Wärmebehandlung der Vergütungsstähle. Ziel ist es ein Werkstück mit hoher Festigkeit und gleichzeitig großer Zähigkeit zu erhalten.
Nr. 0090	Wie wird das Vergüten durchgeführt? 	-Erwärmen auf Härtetemperatur -Halten und Abschrecken -Anschließend Anlassen mit höherer Anlasstemperatur als beim Härten (500°C bis 700°C)
Nr. 0091	Welche Maschinenteile werden meist vergütet? 	-Achsen -Wellen -Getriebe- und Kurbelwellen -Schrauben -Zahnräder -Hebel -Gestänge....
Nr. 0092	Welchen Kohlenstoﬀgehalt enthalten Vergütungsstähle? 	Vergütungsstähle enthalten 0,2% bis 0,6% Kohlenstoﬀ.  8068.29368  Stand: 01.12.2021  Seite 36 / 98
Nr. 0093	Was wird unter dem Begriﬀ „Härten“ verstanden? 	Härten ist eine Wärmebehandlung, die Stähle hart und verschleißfest macht.
Nr. 0094	Aus welchen Arbeitsgängen besteht das Härten? 	-Erwärmen auf Härtetemperatur -Halten auf Härtetemperatur -Abschrecken -Anschließendes Anlassen auf Gebrauchshärte
Nr. 0095	Welche Abschreckmittel werden angewendet? 	-Bewegte Luft -Stickstoﬀ -Warmbad-Abschreckbäder -Öl -Wasser-Öl-Emulsionen -Wasser  Die Abschreckwirkung mit Wasser ist am Schroﬀsten, mit bewegter Luft am Mildesten.
Nr. 0096	Was ist Randschichthärten?  8068.29406 	Beim Randschichthärten wird eine dünne Außenschicht des Werkstückes, aus härtbarem Stahl, durch starke Wärmezufuhr rasch erwärmt und durch sofort anschließendes Abschrecken gehärtet.
Nr. 0097	Welche Randschichthärteverfahren gibt es? 	-Induktionshärten -Flammhärten -Laserhärten -Plasmastrahlhärten  Bild siehe Europa-Lehrmittel Fachkunde Metall  Stand: 01.12.2021  Seite 37 / 98
Nr. 0098	Was ist Nitrierhärten? (Nitrieren) 	Beim Nitrieren wird eine dünne Randschicht des Werkstückes mit Stickstoﬀ angereichert, wobei eine sehr harte und verschleißfeste Randzone entsteht. Die Nitrierschicht erreicht die höchste bei Stahl erreichbare Härte, bis zu 1200 HV. Der Werkstückkern bleibt unverändert.Meistens werden die Werkstücke vor dem Nitrieren noch vergütet um die Festigkeit und Zähigkeit des Werkstückkerns zu verbessern.
Nr. 0099	Wo werden nitrierte Teile verwendet? 	-Als Messspindeln -Steuernocken -Extruderschnecken -Biegestempel -Formeinsätze
Nr. 0100	Was ist Einsatzhärten?  8068.29433 	Beim Einsatzhärten wird die Randschicht eines kohlenstoﬀarmen Stahls mit Kohlenstoﬀ angereichert und anschließend gehärtet.  Man erhält dadurch ein Werkstück mit gehärteter Randschicht und einem ungehärteten zähen Kern.  Zum Einsatzhärten werden Stähle mit 0,1% - 0,2% Kohlenstoﬀ verwendet.
Nr. 0101	Wie wird aufgekohlt?  8068.29435 	Das Anreichern mit Kohlenstoﬀ, Aufkohlen genannt, erfolgt durch Glühen der Werkstücke im kohlenstoﬀabgebenden Einsatzmitteln über mehrere Stunden bei 880°C bis 980°C.  Dabei dringt Kohlenstoﬀ in die Randschicht ein, die dadurch härtbar wird.  Als Einsatzmittel verwendet man feste, ﬂüssige und gasförmige Stoﬀe.
Nr. 0102	Wie erhalten die aufgekohlten Werkstücke die gewünschten Gebrauchseigenschaften?  Stand: 01.12.2021  Seite 38 / 98  	Durch das anschließende Härten und Anlassen. Nur die aufgekohlte Randschicht wird gehärtet, der Werkstückkern bleibt ungehärtet und zäh.
Nr. 0103	Was ist Carbonitrieren?  8068.29458 	Carbonitrieren ist eine Kombination von Einsatzhärten und Nitrierhärten. Beim Carbonitrieren wird die Randschicht des Werkstoﬀes im Gasaufkohlungsofen gleichzeitig aufgekohlt und nitriert. Anschließend wird durch Erwärmen und Abschrecken gehärtet.
Nr. 0104	Wo wird die HRB-Prüfung (Stahlkugel) angewendet? 	-Bei ungehärteten Stählen -Leichtmetalle -Cu-Werkstoﬀe und Legierungen
Nr. 0105	Welche Werkstoﬀe können mit der Brinellhärteprüfung geprüft werden? 	Mit dieser Härteprüfung können nur weiche und mittelharte Werkstoﬀe geprüft werden.
Nr. 0106	Wie ist der Ablauf der Härteprüfung nach Brinell? 	Eine Kugel aus gehärtetem Stahl oder Hartmetall wird mit einer Prüfkraft in die Probe eingedrückt. Gemessen wird der Durchmesser des Kugeleindrucks.Der Härtewert HB wird dann mittels Tabelle ermittelt.  Bild siehe Europa-Lehrmittel Fachkunde Metall
Nr. 0107	Wo wird die HRC-Prüfung angewendet? 	-Gehärtete Stähle und Legierungen -Hartmetalle
Nr. 0108	Wie wird eine Härteprüfung nach Rockwell durchgeführt? 	Bei einer Härteprüfung nach Rockwell wird eine gehärtete Stahlkugel (HRB) oder ein Diamantkegel mit 120° (HRC) in die Probe eingedrückt. Der Härtewert ergibt sich aus der Eindringtiefe, der direkt am Messgerät abgelesen wird.
Nr. 0109	Welche Werkstoﬀe werden nach Vickers geprüft? 	Bei der Vickershärteprüfung können sowohl harte als auch weiche, dünne wie auch dicke Werkstoﬀe geprüft werden. Maßgebend ist die jeweilige Prüfkraft die zur Härteprüfung angewendet wird.
Nr. 0110	Wie ist der Ablauf der Härteprüfung nach Vickers? 	Die Spitze einer 4-seitigen Pyramide aus Diamant mit einem spitzen Winkel von 136° wird in die Probe eingedrückt. Die Vickershärte errechnet sich aus der Prüfkraft und der Pyramideneindruckdiagonalen. Der Vickershärtewert HV wird dann aus einer Tabelle abgelesen.  Bild siehe Europa-Lehrmittel Fachkunde Metall
Nr. 0111	Was wird mit der Feilprobe festgestellt? 	Mit der Feilprobe kann herausgefunden werden, ob ein Werkstoﬀ hart oder weich ist. Rutscht die Feile beim Feilversuch über das Werkstück, ist es mit Sicherheit ein harter Werkstoﬀ.
Nr. 0112	Welche Ziele haben Werkstoﬀprüfungen? 	-Die Bestimmung des Materials nach der Zusammensetzung, z.B. chemische Werkstoﬀanalyse -Die Bestimmung der Eigenschaften der Werkstücke, z.B. Härte, Festigkeit, Verformbarkeit, Material -Überprüfung fertiger Werkstücke auf Fehler, z.B. Risse, Schlackeneinschlüsse -Die Ermittlung einer Schadensursache, z.B. Prüfung eines Bruches, um in Zukunft ähnliche Schäden zu vermeiden
Nr. 0113	Welche einfachen Werkstoﬀprüfungen werden angewendet?  Stand: 01.12.2021  Seite 40 / 98  	-Beurteilung nach Aussehen -Klangprobe -Feilenprobe -Magnetprobe
Nr. 0114	Welche Beanspruchungsarten gibt es in der Festigkeitslehre? 	-Zug -Druck -Abscherung -Biegung -Verdrehung (Torsion) -Knickung
Nr. 0115	Wie wird die Festigkeit erreicht?  8068.29502  8068.29503 	-Mit zunehmendem C-Gehalt steigt die Festigkeit -Legierungsanteile wie Si, Mn, Cr, Ni, W, V, Co und Mo erhöhen die Festigkeit -Durch Wärmebehandlung (Vergüten)
Nr. 0116	Was kann mit der Magnetprobe festgestellt werden? 	Ob Stähle magnetisch oder antimagnetisch sind. Der überwiegende Teil der rostbeständigen Stähle ist antimagnetisch (austenitischer Stahl).
Nr. 0117	Was ist unter dem Begriﬀ "Korrosion" zu verstehen? 	Unter Korrosion versteht man die von der Oberﬂäche ausgehende Zerstörung metallischer Werkstoﬀe durch chemische und elektrochemische Reaktionen.
Nr. 0118	Nenne Maßnahmen zum Korrosionsschutz! 	-Auswahl geeigneter Werkstoﬀe -Korrosionsgerechte Konstruktion  Stand: 01.12.2021  Seite 41 / 98  -Verminderung der Aggressivität der umgebenden Stoﬀe -Korrosionsschutzschichten  Bild siehe Europa-Lehrmittel Fachkunde Metall.
Nr. 0119	Was gibt es für Korrosionsschutzmöglichkeiten? 	-Petrowachs: für Einlagerungen -Lanolin: für Einlagerungen -Klarlack: für Einlagerungen -Brünieren, Phosphatieren: für Innenanwendung -Lackieren, Spritzen, Pulverbeschichten: für Außenanwendung -Feuerverzinken, Galvanisieren (Zn, Ni, Cr): für Außenanwendung -Anodisieren (Eloxalschicht): für Aluminium -Reinigen und tauchen in Schutzöl -Nitrieren -Nitrocarburieren -Verchromen
Nr. 0120	Erkläre den Begriﬀ "Eloxieren"!  8068.29512 	Beim Eloxieren wird die natürliche Korrosionsbeständigkeit von Aluminium durch anodische Oxidation zusätzlich verbessert.  Bei diesem Verfahren bildet sich auf dem AL-Bauteil eine harte, korrosionsbeständige und fest haftende Oxidschicht.  Thema: Fertigungstechnik
Nr. 0121	Was ist beim Anfertigen einer Bohrung zu beachten 	Erläuterung über:   Bohrwerkzeuge, Schneidengeometrie, Schnittdaten, Materialien, Spannmöglichkeiten des Werkzeuges und Werkstückes.
Nr. 0122	Wie ist ein Spiralbohrer aufgebaut? 	 Stand: 01.12.2021  Seite 42 / 98
Nr. 0123	Was ist Reiben?  8068.29232 	Reiben ist ein Aufbohren mit geringer Spanungsdicke zur Herstellung passgenauer Bohrungen mit hoher Oberﬂächengüte.
Nr. 0124	Nenne einige verschiedene Reibwerkzeuge! 	-Handreibahle -Maschinenreibahle -Kegelreibahle -Verstellbare Reibahle -Gerade genutete Reibahle -Drallgenutete Reibahle mit Rechtsdrall -Drallgenutete Reibahle mit Linksdrall
Nr. 0125	Warum verwendet man Reibahlen mit gerader Zähnezahl und ungleicher Teilung? 	-Um Schwingungen, Rattermarken und Kreisformfehler zu vermeiden -Einfaches Messen des Durchmessers
Nr. 0126	Worauf ist beim Schneiden von Gewinden in Grundlöcher zu achten? 	-Grundloch tiefer als nutzbare Gewindelänge bohren, da das Gewinde nicht bis auf den Grund der Bohrung geschnitten werden kann -Gewindebohrer mit Drall verwenden
Nr. 0127	Erkläre den Begriﬀ "Drehen"!  8068.29241 	Drehen ist ein zerspanendes Fertigungsverfahren mit einer geometrisch bestimmten Schneide und kreisförmiger Schnittbewegungen. Meist führt das Werkstück die Drehbewegung aus. Das fest eingespannte Werkzeug (Drehmeißel) wird am drehenden Werkstück mit Hilfe des Werkzeugschlittens entlang bewegt.
Nr. 0128	Welche Werkstücke werden auf der Planscheibe gespannt? 	Große und unregelmäßig geformte Werkstücke. Achtung: bei Unwucht - Gegengewicht anbringen und Drehzahl verringern
Nr. 0129	Wie müssen Werkstücke zwischen den Spitzen eingespannt werden? 	 Richtiger Spanndruck Mitnahme des Werkstückes erfolgt durch Mitnehmer (Drehherz) Stirnseiten - Mitnehmer Bei festen Spitzen unbedingt schmieren
Nr. 0130	Welche Vorteile bieten Stirnseitenmitnehmer? 	-Geringe Fliehkräfte -Werkstück kann über die ganze Länge bearbeitet werden -Hohe Rundlaufgenauigkeit -Sehr schnelles, sicheres Spannen
Nr. 0131	Wozu dient der Setzstock (Lünette)? 	-Zum Abstützen längerer schlanker Wellen (mitlaufender Setzstock) -Zum Innendrehen, Plandrehen und Bohren langer Teile (feststehender Setzstock)
Nr. 0132	Welche Werkstücke werden auf Kopfdrehmaschinen bearbeitet? 	Werkstücke mit großem Durchmesser und geringer Länge.
Nr. 0133	Welche Möglichkeiten gibt es Exzenter zu drehen? 	-Zwischen den Spitzen -Auf der Planscheibe -Auf einem Drehdorn -Mit speziellen Vorrichtungen
Nr. 0134	Wie kann das Zustellen des Gewindedrehmeißels beim Schneiden von Spitzgewinden auf der Drehmaschine erfolgen? 	-Bei kleiner Steigung und feinen Spänen durch Zustellen mit dem Planschlitten. -Durch wechselseitiges Zustellen mit dem Planschlitten unter gleichzeitigem Verstellen des Oberschlittens. -Mit dem schräggestellten Oberschlitten, wobei der Einstellwinkel gleich 90° - halber Flankenwinkel ist.
Nr. 0135	Nenne verschiedene Querschnittsformen für Feilen! 	-Flachfeilen -Vierkantfeilen -Dreikantfeilen -Halbrundfeilen -Rundfeilen
Nr. 0136	Wozu werden Diamantfeilen verwendet?  8068.29287  Stand: 01.12.2021  Seite 45 / 98  	Für die Bearbeitung von gehärteten Werkstücken.
Nr. 0137	Erkläre den Begriﬀ "Räumen"!  8068.29299 	Räumen ist ein spanendes Verfahren mit mehrschneidigem Werkzeug. Dabei erhält das Werkzeug eine bestimmte Kontur, die im Räumwerkzeug vorgegeben ist.
Nr. 0138	Nenne die Vor- und Nachteile des Räumens gegenüber Stoßen! 	Vorteile: -Maßgenaues Herstellen von Passfedernuten -Schnelles Arbeiten möglich -Kurze Rüstzeit -Mehrere gleiche Teile können gleichzeitig geräumt werden  Nachteile: -Teure Werkzeuge -Für jede Form muss ein eigenes Werkzeug verwendet werden -Erst bei Serien wirtschaftlich
Nr. 0139	Wie ist ein Räumwerkzeug aufgebaut? 	-Schaft -Einführung -Zahnung: Schruppzähne, Schlichtzähne, Reservezähne -Führungsstück -Endstück
Nr. 0140	Was ist Schleifen? 	 8068.29316  Schleifen ist ein spanendes Fertigungsverfahren zur Bearbeitung von Oberﬂächen oder zum Trennen von Werkstoﬀteilen mit Schleifmitteln und gebundenem Schleifkorn. Schleifen ist eine Zerspanungsart mit geometrisch unbestimmten Schneiden.
Nr. 0141	Welches sind die wichtigsten Schleifmittel? 	Künstliche Schleifmittel: -A Normalkorund, Halbkorund, Edelkorund -C Siliziumkarbid -CBN Bornitrid  Natürliche Schleifmittel -D Diamant, Ölsandstein, Schmirgel
Nr. 0142	Was bedeutet Körnung (z.B. 40) bei einem Korundschleifmittel? 	Die Körnung gibt Aufschluss über Größe des Schleifkorns und entspricht der Maschenzahl (40) des Siebes auf 1 Inch Länge.
Nr. 0143	Welche Aufgabe hat die Bindung einer Schleifscheibe? 	Die Bindung hat den Zweck, die einzelnen Körner so lange festzuhalten, bis sie stumpf geworden sind.
Nr. 0144	Was ist die Härte der Schleifscheibe? 	Der Widerstand des Kornes gegen das Ausbrechen aus dem Kornverband (Kornhaltekraft).
Nr. 0145	Warum müssen Schleifscheiben gewuchtet werden? 	Bei großen, breiten Schleifscheiben und besonders bei hohen Umfangsgeschwindigkeiten ist das Auswuchten äußerst wichtig, da die Fliehkräfte der Unwucht drastisch mit der Drehzahl wachsen (Unfallgefahr, schlechte Oberﬂächengüte des Werkstückes).
Nr. 0146	Welche Angaben sind in einer Schleifkörperbezeichnung enthalten?  Stand: 01.12.2021  Seite 47 / 98  	-ISO-Grundform (gerade Schleifscheibe usw.) -Außendurchmesser -Breite -Bohrungsdurchmesser -SchleifmittelKörnung -Härtegrad -Gefügekennziﬀer -Bindung -Zulässige Umfangsgeschwindigkeit 35 m/s (Schleifbock, Flächenschleifmaschine) -Zulässige Umfangsgeschwindigkeit 80 m/s (Winkelschleifer)
Nr. 0147	Was für Schleifmaschinen gibt es? 	-Schleifbock -Bandschleifmaschinen -Werkzeugschleifmaschinen -Flachschleifmaschinen -Rundschleifmaschinen -Koordinatenschleifmaschinen -Proﬁlschleifmaschinen -CNC – Schleifmaschinen
Nr. 0148	Was ergeben sich durch CNC - Schleifmaschinen für Bearbeitungsmöglichkeiten? 	CNC- Bahnsteuerrungen mit vier und mehr gleichzeitig steuerbaren Achsen erweitern die Schleifmöglichkeiten, z.B. -Gekrümmte Bahnkurven in Tischlängsrichtung -Bahngesteuertes Formschleifen von Proﬁlen -Bahngesteuertes Abrichten (Proﬁlieren) von Schleifscheiben mit Diamant- Abrichtern  Bild siehe Europa-Lehrmittel Fachkunde Metall.
Nr. 0149	Wodurch unterscheidet sich das Honen vom Läppen? 	Honen ist ein Spanen mit gebundenem Korn unter ständiger Flächenberührung des Werkzeuges (Honstein).  Läppen ist Spanen mit losem Korn, das zwischen dem formübertragenden Läppwerkzeug und dem Werkstück in ungerichteten Wirkbahnen abrollt.
Nr. 0150	Wie entstehen die gekreuzten Bearbeitungsriefen beim Honen?  Stand: 01.12.2021  Seite 48 / 98  	Durch Überlappung der Dreh- und Axialbewegung bei Werkstoﬀabtrag.
Nr. 0151	Welche Vorteile haben gehonte Zylinder? 	Sie haben eine hervorragende Ölhaftung.
Nr. 0152	Was ist Fräsen? 	 8068.29354  Fräsen ist ein spanabhebendes Fertigungsverfahren mittels eines Fräswerkzeuges, das mit mehreren geometrisch bestimmten Schneiden ausgestattet ist. Die Hauptbewegung wird durch das Schneidwerkzeug zum Herstellen von Flächen und Nutten ermöglicht.
Nr. 0153	Benenne einige Fräswerkzeuge 	 8068.29363  Stand: 01.12.2021  Seite 49 / 98
Nr. 0154	Welches sind die in der Praxis häuﬁgst verwendeten Beschichtungsarten?  Stand: 01.12.2021  Seite 50 / 98  	TiN - Beschichtung   =  Titannitrid TiCN - Beschichtung  =  Titancarbonitrid TiALCN - Beeschichtung  =  Titanaluminiumcarbonitrid (für gehärtete Werkstoﬀe) Diamant - Beschichtung  (für Graphit-Bearbeitung)  Steigerung der Oberﬂächenhärte von 950 HV (HSS) auf über 2000 HV (TiN) bzw. 3000 HV (TiCN) und 3600 HV (TiALCN) unter Beibehaltung der Zähigkeitseigenschaften des Grundkörpers.
Nr. 0155	Welche Schaftformen besitzen Frässpannzeuge? 	Steilkegelschäfte oder Hohlschaftkegel, je nach Ausführung des Spindelkopfs.
Nr. 0156	Welche Merkmale kennzeichnen eine Universal-CNC-Fräsmaschine? 	-Ausrüstung mit CNC-Bahnsteuerung -Universalwinkeltisch, ev. austauschbar gegen NC-Rundtisch oder NC-Teilapparat -Spielfreie Achsantriebe -Für jede Achse eigene Vorschubantriebe mit direkt messenden Wegmeßsystemen -Horizontalspindel -Schwenkbarer Vertikalfräskopf -Werkzeugschnellspanneinrichtung -Werkzeugmagazin mit automatischem Werkzeugwechsler
Nr. 0157	Welche Arbeiten können mit einem Universalteilapparat ausgeführt werden? 	Es können Fräs- und Teilungsarbeiten ausgeführt werden, wie z.B. -Sechskantfräsen -Keilwellen -Wendelnuten -Zahnräder  Man unterscheidet direktes und indirektes Teilen. Das Übersetzungsverhältnis ist vorwiegend 40 : 1.
Nr. 0158	Was ist funkenerosive Bearbeitung? 	Beim Funkenerodieren wird der Werkstoﬀ durch die erodierende Wirkung (elektrische Entladungen) zwischen Werkstück- und einer Werkzeugelektrode abgetragen. Dabei schmilzt der Werkstoﬀ auf, wird teilweise verdampft und durch mechanische und elektrische Kräfte entfernt.  Stand: 01.12.2021  Seite 51 / 98
Nr. 0159	Welche Bearbeitungen können beim funkenerosiven Schneiden durchgeführt werden? 	Beim funkenerosiven Schneiden, auch Drahterodieren genannt, dient als Werkzeugelektrode ein ablaufender Kupfer- oder Messingdraht mit einem Durchmesser von 0,02 - 0,3 mm. Mit diesem ablaufenden Metalldraht können an Werkstücken genaue Bohrungen und komplizierte Durchbrüche mit einer Maßgenauigkeit unter 0,005 mm gefertigt werden.
Nr. 0160	Welche Bearbeitungen können beim funkenerosiven Senken durchgeführt werden? 	Mit dem funkenerosiven Senken können Bohrungen, Durchbrüche und Einsenkungen (Gravuren) auch aus dem Vollen gefertigt werden.
Nr. 0161	Worin liegen die Vorteile der CNC-gesteuerten Maschinen? 	-Gleichbleibende Bearbeitungsqualität -Geringe Ausschuss- und Kontrollkosten -Kürzere Fertigungszeiten -Ausbaumöglichkeiten zu weiterer Automation (z.B. durch Werkzeugwechsler) -Herstellung schwieriger Konturen -Speichern einmal erstellter Programme
Nr. 0162	Welche Steuerungsarten von CNC-Maschinen gibt es? 	Bei den NC-Maschinen unterscheidet man: -Punktsteuerungen: bei Bohrmaschinen, Punktschweißmaschinen oder Stanzmaschinen -Streckensteuerungen: bei einfachen Werkzeugmaschinen und in der Montagetechnik -Bahnsteuerungen: bei fast allen CNC-Werkzeugmaschinen, wie z.B. Fräsmaschinen, Drehmaschinen oder Bearbeitungszentren; hier kann zwischen 2-, 3- oder mehrachsigen Bahnsteuerungen unterschieden werden.
Nr. 0163	Welche Null- bzw. Bezugspunkte gibt es? 	-Werkstücknullpunkt W -Maschinennullpunkt M  Stand: 01.12.2021  Seite 52 / 98  -Referenzpunkt R -Programmnullpunkt P
Nr. 0164	Erkläre den Aufbau eines NC-Programmes! 	Reihenfolge beim Satzaufbau:  Satznummer                     N                          N1, Satz 1 Wegbedingungen              G                          G0, G1, G2, G3 Koordinaten                     X, Y, Z                   Bewegungen in den Achsen Vorschub                         F                           mm/min Spindeldrehzahl                S                           U/min Werkzeug                        T                           T1 => Werkzeug 1 Zusatzfunktion                 M                           M3 => Spindel rechtsdrehend
Nr. 0165	Erkläre den Begriﬀ "Fügen"!  8068.29414  8068.29417 	Durch Fügen werden zwei oder mehrere Werkstücke miteinander verbunden. Nach der Wirkungsweise unterscheidet man formschlüssiges, kraftschlüssiges, vorgespannt formschlüssiges und stoﬀschlüssiges Fügen. Man unterscheidet zwischen lösbaren und unlösbaren Verbindungen.   Lösbar:  Formschlüssige Verbindungen -Passfedern -Keilwellen -Passschrauben -Stiften -Bolzen -Nieten (unlösbar) Kraftschlüssige Verbindungen -Schraubenverbindungen -Klemmverbindungen -Kegelverbindungen -Einscheibenkupplungen Vorgespannt formschlüssige Verbindungen -Keilverbindungen -Stirnzahnverbindungen -Kegelverbindungen mit Scheibenfedern   Unlösbar:  Stoﬀschlüssige Verbindungen -Schweißverbindungen -Klebeverbindungen -Lötverbindungen  Stand: 01.12.2021  Seite 53 / 98  Bild siehe Europa-Lehrmittel Fachkunde Metall
Nr. 0166	Nenne die Bestimmungsgrößen bei Gewinden! 	-Gewindeproﬁl -Außendurchmesser -Steigung -Kerndurchmesser -Flankendurchmesser -Flankenwinkel
Nr. 0167	Nach welchen Kriterien werden Gewindearten eingeteilt? 	Einteilung nach: -Verwendungszweck -Proﬁl -Drehsinn und -Gangzahl -Metrisch und Zoll bzw. Withworth  8068.29436  Einteilung nach dem Verwendungszweck: -Befestigungsgewinde, zB.: Spitzgewinde (selbsthemmend) -Bewegungsgewinde, zB.: Trapez- oder Sägegewinde bei Antrieben von Werkzeugmaschinen, KugelgewindeSpindeln (nicht selbsthemmend)  Einteilung nach dem Gewindeproﬁl: -Spitzgewinde -Trapezgewinde -Sägegewinde -Flachgewinde -Rundgewinde -Sondergewinde (zB.: Flaschenverschlüsse)  Einteilung nach dem Drehsinn: -Rechtsgewinde -Linksgewinde -Linksgewinde sind mit den Buchstaben LH (left hand) zusätzlich gekennzeichnet  Einteilung nach der Gangzahl: -Eingängige Gewinde -Mehrgängige Gewinde zB.: TR32 x 18 T6 (18 : 6 = dreigängiges Trapezgewinde mit 32mm Nenndurchmesser, 18mm Steigung und 6mm Teilung)
Nr. 0168	Welche Flankenwinkel haben metrische ISO-Gewinde und Withworth-Gewinde?  Stand: 01.12.2021  Seite 54 / 98  	Metrische ISO-Gewinde: 60° Flankenwinkel Withworth-Gewinde: 55° Flankenwinkel
Nr. 0169	Wie unterscheiden sich Regelgewinde von Feingewinden? 	-Feingewinde haben eine kleinere Steigung als Regelgewinde. -Bei einem Feingewinde wird zusätzlich zum Nenndurchmesser die Steigung angegeben, z.B. M 16 x 1,5.
Nr. 0170	Wie werden Schraubenverbindungen unterteilt? 	-Durchsteckschrauben -Einziehschrauben -Stiftschrauben  Bild siehe Europa-Lehrmittel Fachkunde Metall.
Nr. 0171	Welche Kopﬀormen von Schrauben gibt es? 	-Sechskantschrauben -Zylinderschrauben mit Innensechskant -Senkschrauben mit Innensechskant -Zylinderschrauben und Senkkopfschrauben mit Schlitz, Kreutzschlitz und Torx
Nr. 0172	Wie werden Schrauben nach der Schaftform eingeteilt? 	-Stiftschrauben -Dehnschrauben -Passschrauben -Gewindestifte -Blechschrauben -Bohrschrauben -Holzschraube  Bild siehe Europa-Lehrmittel Fachkunde Metall.
Nr. 0173	Erkläre die Schraubenbezeichnung "Festigkeitsklasse 12.9"! 	Mindestzugfestigkeit: Rm = 12 . 100 N/mm² = 1200 N/mm² (1. Zahl (12) wird mit 100 multipliziert)  Mindeststreckgrenze: Re = 12 . 10 . 9 N/mm² = 1080 N/mm² (wird durch Multiplikation der 1. Zahl (12) mit dem zehnfachen Wert der 2. Zahl (9) ermittelt)
Nr. 0174	Nenne Anwendungsgebiete von Schrauben aufgrund ihrer Schaftform! 	Stiftschrauben - Turbinen - Motoren und - Lagergehäuse Innengewinde werden geschont  Dehnschrauben - Pleuelstangen - Hochdruck-Flanschverbindungen  Passschrauben - werden eingesetzt, wenn die Schraubenverbindung Querkräfte aufnehmen muss oder wenn die Lage der Werkstücke zueinander gesichert werden soll.  Gewindestifte - Zur Sicherung der Lage von Werkstücken mit Naben auf Wellen und  Achsen.  Blechschrauben - Scharfkantiges Gewinde mit großer Steigung   (Blechverbindungen bis 2,5mm)  Bohrschrauben - Werkstoﬀverbindungen bis 10mm Dicke   (zusätzliche Bohrspitze am Schaftanfang zum Bohren des   Kernloches).
Nr. 0175	Wie werden Muttern ihrer Form nach unterteilt? 	-Sechskantmutter: In Verbindung mit Sechskantschrauben, Schlitzschrauben und Stiftschrauben  -Hutmutter: Verhindern Beschädigung und Korrosion des Gewindeendes; schützen vor Verletzung durch scharfe Schraubenenden  -Rändelmutter: Wenn die Schraubenverbindung oft von Hand gelöst werden muss, z.B. bei Vorrichtungen  -Überwurfmutter: Für Rohrverschraubungen  -Kronenmutter: Wenn die Schraubenverbindung mit Splinten gesichert werden soll  Stand: 01.12.2021  Seite 56 / 98  -Flügelmutter: Wenn die Schraubenverbindung oft gelöst werden muss, z.B. bei Vorrichtungen  -Nutmutter: Zum Ein- und Nachstellen des axialen Spiels und zum Befestigen von Wälzlagern auf Wellen  -Ringmutter: Als Ösen zum Transport von Maschinen  Bild siehe Europa-Lehrmittel Fachkunde Metall.
Nr. 0176	Welche Hauptgruppen von Schraubensicherungen gibt es? 	Setzsicherungen - Federring - Zahnscheibe - Fächerscheibe - Spannscheibe bzw. Tellerfeder  Losdrehsicherungen - Sperrzahnschraube - Klebstoﬀbeschichtetes Gewinde  Verliersicherungen - Kronenmutter mit Splint - Sicherungsblech - Geschlitzte Mutter - Mutter mit Kunststoﬀring - Drahtsicherung - Schraubengewinde mit aufgesinterter Polyamidschicht  Bild siehe Europa-Lehrmittel Fachkunde Metall.
Nr. 0177	Welche Werkzeuge kommen beim Anziehen von Schraubenverbindungen zum Einsatz? 	-Maulschlüssel -Ringschlüssel -Steckschlüssel -Hackenschlüssel -Schraubendreher für Schlitz, Kreuzschlitz und Torx -Winkelschraubendreher -Messschlüssel (Drehmomentschlüssel) -Impulsschrauber (Druckluftschrauber) -Elektronisch und hydraulisch gesteuerter Schrauber (streckgrenzenkontrolliertes Anziehen) -Spannzylinder
Nr. 0178	Wie werden Stifte ihrer Form nach unterteilt?  Stand: 01.12.2021  Seite 57 / 98  	-Zylinderstifte -Kegelstifte -Spannstifte -Zylinder- und Kegelkerbstifte  Die Auswahl richtet sich nach: -Dem Verwendungszweck -Der verlangten Genauigkeit -Den Kosten, die bei der Herstellung der Stiftverbindung entstehen
Nr. 0179	Welche Aufgaben haben Stiftverbindungen? 	Mit Stiftverbindungen werden lösbare Verbindungen hergestellt. Sie werden meist auf Abscherung beansprucht.  Nach dem Verwendungszweck unterscheidet man:  -Passstifte: sichern die Lage von 2 Bauteilen zueinander.  -Befestigungsstifte: verbinden 2 oder mehrere Bauteile kraft- und formschlüssig und können somit Kräfte und Drehmomente übertragen.  -Abscherstifte: verhindern die Beschädigung von Bauteilen, indem sie als Soll-Bruchstelle bei unzulässiger Beanspruchung den Kraftﬂuss unterbrechen.
Nr. 0180	Nach welchen Kriterien werden Stifte ausgewählt? 	-dem Verwendungszweck -der verlangten Genauigkeit -den Kosten
Nr. 0181	Welche Verjüngung besitzen Kegelstifte? 	Kegelstifte haben eine genormte Kegelverjüngung. C = 1 : 50 (auf 50 mm Länge 1 mm Durchmesserunterschied)  8068.29464
Nr. 0182	Welche Verbindungsarten werden angewendet? 	Formschluss-Verbindungen:  Stand: 01.12.2021  Seite 58 / 98  übertragen Kräfte (Drehmomente) durch ineinander passende Formen. Dabei ist eine axiale Verschiebung von Welle und Nabe möglich.  Vorgespannte Formschluss-Verbindungen: übertragen Kräfte durch Form- und durch Kraftschluss  Kraftschluss-Verbindungen: übertragen Kräfte durch Reibung zwischen Welle und Nabe.  Stoﬀschluss-Verbindungen: übertragen Kräfte, indem Welle und Nabe miteinander verschweißt, verlötet oder verklebt werden. Sie sind meist nicht mehr lösbar.
Nr. 0183	Nenne Beispiele für Formschluss-Verbindungen! 	-Passfederverbindung -Keilwellenverbindungen -Zahnwellenverbindungen -Kerbzahn- und Evolventenzahnverbindungen -Polygonwellenverbindungen
Nr. 0184	Nenne Beispiele für vorgespannte Formschluss-Verbindungen! 	Keilverbindungen: Einsatz im Großmaschinenbau und bei rauem Betrieb (Neigung 1 : 100)  Die Keile werden unterteilt in: -Treibkeile -Einlegkeile -Tangentialkeile  Stirnzahnverbindungen:sind selbstzentrierende Verbindungselemente, bei denen an Planﬂächen radial angeordnete Zähne ineinander greifen.  Anwendungsbeispiele: -Bauteile mit hoher Teilgenauigkeit für Rundschalttische -Wegen des geringen Platzbedarfes in Getrieben zur Verbindung von Wellen mit Flanschen eingesetzt.
Nr. 0185	Nenne Beispiele für Kraftschlussverbindungen! 	Klemmverbindungen: besitzen geschlitzte oder geteilte Naben, die durch Schrauben mit der Welle verspannt werden.  Kegelverbindungen: bestehen aus einem Wellenaußenkegel und einem Naben-Innenkegel. Durch axiales Spannen werden große  Stand: 01.12.2021  Seite 59 / 98  Normalkräfte hervorgerufen, die entsprechend große Reibungskräfte am Umfang verursachen.
Nr. 0186	Auf welche Weise können Naben gegen axiales Verschieben gesichert werden? 	Die Sicherung erfolgt meist formschlüssig durch genormte Sicherungselemente, wie z.B.: -Stellringe -Kegelstifte -Sicherungsringe -Sprengringe -Sicherungsscheiben  Bild siehe Europa-Lehrmittel Fachkunde Metall, 53. Auﬂage, Seite 383 Bild siehe Europa-Lehrmittel Fachkunde Metall, 54. Auﬂage, Seite 362
Nr. 0187	Wie entstehen Pressverbindungen? 	Pressverbindungen entstehen, wenn beim Fügen von Bauteilen Übermaß zwischen den Passﬂächen vorhanden ist. Pressverbindungen übertragen Kräfte und Drehmomente kraftschlüssig.
Nr. 0188	Erkläre den Begriﬀ "Dehnen"!  8068.29496 	Wenn die Außenteile wegen ihrer Größe oder Form nicht erwärmt werden können oder Gefügeveränderungen auftreten würden, wird das Innenteil soweit abgekühlt, bis es sich leicht in das Außenteil einfügen lässt.  Als Kühlmittel dienen: -Trockeneis (festes Kohlendioxid, bis minus 79°) -Flüssiger Stickstoﬀ (bis minus 190°)
Nr. 0189	Erkläre den Begriﬀ "Schrumpfen"! 	Beim Schrumpfen wird das Außenteil erwärmt und über das Innenteil geschoben. Während des Erkaltens bildet sich die Pressverbindung durch Schrumpfen des Außenteiles.  Zur Erwärmung dienen: -Induktive Anwärmgeräte -Temperaturgesteuerte Anwärmplatten -Ölbäder -Heißluftöfen -Gasbrenner  Stand: 01.12.2021  Seite 60 / 98
Nr. 0190	Welche Arbeitsregeln sind beim Anwärmen und Kühlen von Werkstücken für eine Pressverbindung zu beachten? 	-Vorgeschriebene Anwärmtemperaturen sind genau einzuhalten, um Gefügeveränderungen zu vermeiden. -Große, sperrige Teile sind gleichmäßig zu erwärmen, da sie sich sonst verziehen. -Wärmeempﬁndliche Teile, z.B. Dichtungen müssen vor dem Erwärmen entfernt werden. -Bei Arbeiten mit Kühlmitteln sind die Sicherheitsvorschriften zu beachten.
Nr. 0191	Nenne die Vor- und Nachteile einer Nietverbindung! 	Vorteile: -Keine Gefügeveränderung -Kein Verzug -Keine Festigkeitsminderung -Unterschiedliche Werkstoﬀe können miteinander verbunden werden -Verbindung kann auch bei einseitiger Zugänglichkeit hergestellt werden -Geringer Energieverbrauch -Keine Gesundheitsgefahr  Nachteile: -Überlappungen und -Nieten ergeben eine Gewichtserhöhung -Verbindungsstelle kann je nach Nietkopﬀorm uneben sein
Nr. 0192	Welche Nietarten gibt es? 	-Geschlagene Nieten mit Halbrund-, Senk- und Linsenkopf -Sondernieten, wie z.B. Hohlniete, Dornniete, Pilzniete, Blindeinnietmuttern  Bild siehe Europa-Lehrmittel Fachkunde Metall.  8068.29507
Nr. 0193	Welche Werkzeuge ﬁnden beim Nieten Anwendung? 	-Döpper- bzw. Kopfmacher und Nietzieher für die Handnietung -Elektrische Nietmaschinen -Hydraulische Nietpressen -Drucklufthämmer für die maschinelle Nietung -Dornnietzange (Blindnietzange)
Nr. 0194	Nach welchen Kriterien werden Lötverfahren eingeteilt? 	-Arbeitstemperatur -Lotzuführung -Energieträger zur Erwärmung -Form der Lötstelle (Spaltlöten, Fugenlöten)  Weichlöten: Die Arbeitstemperatur liegt unter 450°C. Das Weichlöten wendet man an, wenn an die Belastbarkeit keine hohen Anforderungen gestellt werden, die Verbindung aber dicht oder leitfähig sein soll. Z.B. elektronische Bauelemente  Hartlöten: Die Arbeitstemperatur liegt über 450°C.  Hochtemperaturlöten: Die Arbeitstemperatur liegt über 900°C. Hochtemperaturlöten ist ein Löten unter Schutzgas oder im Vakuum.  8068.29516  8068.29517
Nr. 0195	Wie erfolgt die Lotzuführung? 	-Lot kann angesetzt werden -Eingelegtes Lot -Tauchlöten
Nr. 0196	Welche Energieträger werden zum Erwärmen der Lötstelle eingesetzt? 	-Gase -Flüssigkeiten -Elektrischer Strom  Anwendungsbeispiele: -Flammlöten -Kolbenlöten -Ofenlöten, für industrielle Fertigung -Induktionslöten, für industrielle Fertigung
Nr. 0197	In welche Hauptgruppen werden Lote unterteilt? 	Weichlote bis 450° Arbeitstemperatur Hartlote über 450° Arbeitstemperatur Hochtemperaturlote über 900° Arbeitstemperatur Lote für Aluminiumwerkstoﬀe  Stand: 01.12.2021  Seite 62 / 98
Nr. 0198	Welche Aufgabe haben Flussmittel? 	Flussmittel lösen Oxide und verhindern weitere Oxidation beim Lötvorgang.
Nr. 0199	Welche Auswirkung hat die Lötspaltbreite? 	Bei richtig bemessener Lötspaltbreite (0,05 - 0,2mm) wird das Lot in den Lötspalt hineingezogen (Kapillarwirkung).
Nr. 0200	Welche Arbeitsregeln sind beim Löten zu beachten? 	-Werkstück und Lot müssen auf Arbeitstemperatur gebracht werden -Der Wirktemperaturbereich des Flussmittels muss unter der Arbeitstemperatur beginnen und über die maximale Löttemperatur hinausreichen -Die Arbeitstemperatur des Lotes muss unter dem Schmelzpunkt des Werkstückes liegen -Die maximale Löttemperatur darf nicht überschritten werden (Verbrennen, Verdampfen des Lotes) -Die Erwärmung soll rasch und gleichmäßig erfolgen
Nr. 0201	Nenne Anwendungen für Klebeverbindungen! 	Flug- und Fahrzeugbau -Verbindung von Konstruktionsteilen -Sichern von Schrauben -Dichten von Fügeﬂächen  Maschinenbau -Befestigen von Buchsen und Lagern -Abdichten von Gehäusen
Nr. 0202	Nenne Vor- und Nachteile des Klebens! 	Vorteile: -Keine Gefügeänderung -Gleichmäßige Spannungsverteilung -Viele Werkstoﬀkombinationen -Dichte Verbindungen  Stand: 01.12.2021  Seite 63 / 98  -Wenig Passarbeit erforderlich  Nachteile: -Große Fügeﬂächen nötig -Geringe Dauerfestigkeit -Geringe Warmfestigkeit -Teilweise lange und komplizierte Aushärtung
Nr. 0203	In welche Hauptgruppen werden Klebstoﬀe unterteilt? 	-Schmelzklebstoﬀe (sie erstarren rein physikalisch durch Abkühlung) -Nassklebstoﬀe (sie härten durch Verdunsten eines Lösungsmittels)  Reaktionsklebstoﬀe sind die am häuﬁgsten angewendeten Klebstoﬀe für Metalle. Sie härten durch eine chemische Reaktion aus. Nach der Verarbeitungstemperatur werden sie in Warm- und Kaltkleber, nach der Zusammensetzung in Ein- und Zwei-Komponenten-Kleber unterteilt. Nassklebstoﬀe (sie härten durch Verdunsten eines Lösungsmittels)
Nr. 0204	Wodurch unterscheiden sich Warm- von Kaltklebern? 	-Kaltkleber härten bei einer Bezugstemperatur von 20°C aus. -Warmkleber benötigen Temperaturen von ca. 120 - 400°C für die Aushärtung.
Nr. 0205	Welche Arbeitsregeln sind beim Kleben zu beachten? 	-Die Fügeﬂächen müssen trocken, sauber, fettfrei und leicht aufgeraut sein. -Der Klebstoﬀauftrag soll unmittelbar nach der Oberﬂächenvorbehandlung erfolgen. -Während der Aushärtung müssen die Teile gegen Verrutschen gesichert werden. -Klebstoﬀe sollen in ungehärtetem Zustand nicht mit der Haut in Berührung kommen. -Die Arbeitsräume sind gut zu lüften (gesundheitsschädliche Dämpfe!). -Herstellerhinweise beachten!
Nr. 0206	Wovon hängt die Haltbarkeit einer Klebeverbindung ab? 	Die Haltbarkeit einer Klebeverbindung hängt von der Adhäsionskraft des Klebestoﬀes an den Fügeﬂächen und an der Kohäsionskraft im Innern der Klebeschicht ab.
Nr. 0207	Wonach richtet sich die Auswahl der Sägeblätter? 	-Grobe Zahnteilung: für weiche Werkstoﬀe und lange Schnittfugen -Feine Zahnteilung: für harte Werkstoﬀe und kurze Schnittfugen
Nr. 0208	Aus welchem Grund dürfen bei hochlegierten Werkstoﬀen (CrNi) nur nichtrostende Werkzeuge verwendet werden? 	Gefahr von Fremdrost – Korrosionsangriﬀ
Nr. 0209	Wie funktionieren Schnappverbindungen? 	Bei Schnappverbindungen verformt sich ein Fügeteil elastisch und verhakt anschließend lösbar oder unlösbar.
Nr. 0210	Welche typischen Befestigungselemente werden für Schnappverbindungen verwendet? 	In Verwendung kommen Klammern und Klipse.  Thema: Maschinen- und Gerätetechnik
Nr. 0211	Zur Verringerung von Reibung und Verschleiß werden Schmierstoﬀe eingesetzt. Welche Eigenschaften sollten sie besitzen? 	-druckfest -haftfähig -alterungsbeständig -geringe Viskositätsveränderung -frei von festen Bestandteilen -geringe innere Reibung -hoher Flamm- bzw. Brennpunkt -säure- und wasserfrei
Nr. 0212	Welche Vor- bzw. Nachteile besitzt eine hydrostatische Schmierung gegenüber einer hydrodynamischen Schmierung?  Stand: 01.12.2021  Seite 65 / 98  	Vorteile: -kein Verschleiß beim Anlauf -geringe Erwärmung durch sehr kleine Reibung -hohe Rundlaufgenauigkeit -kein Ruckgleiten  Nachteile: -aufwendige teure Schmiereinrichtung -sorgfältige Überwachung/ Wartung der Funktion erforderlich
Nr. 0213	Welche Ursachen kann eine starke Erwärmung des Schmieröles haben? 	-zu große Lagerkräfte -falsche Schmiermittelmenge (zu wenig oder zu viel) -Welle und/oder Lager haben eine zu raue Oberﬂäche -zu große Umfangsgeschwindigkeiten
Nr. 0214	Auf was ist bei der Schmierung von Ketten zu achten? 	Bei der Schmierung von Kettentrieben werden fest anhaftende Öle oder Fette verwendet. Bei geschlossenen Gehäusen haben sich Ölbad oder Tropfschmierungen bestens bewährt.
Nr. 0215	Welche Arten von Ölschmierungen werden bei Gleitlagern angewendet? 	-Hydrodynamische Schmierung -Hydrostatische Schmierung (Turbinenlagerung)  Bild siehe Europa-Lehrmittel Fachkunde Metall Sachwortverzeichnis "Lager"
Nr. 0216	Wie können Wälzlager geschmiert werden? 	Ölbadschmierung: Bei der Ölbadschmierung tauchen jeweils die unteren Wälzkörper bis zur Hälfte ins Öl ein. Durch die Drehbewegung des Lagers werden alle Lagerteile mit Öl versorgt.  Ölumlaufschmierung: Bei der Ölumlaufschmierung wird das Öl durch eine Ölpumpe dem Lager zugeführt.  Ölnebelschmierung: Bei besonders schnelllaufenden Wälzlagern wird diese Schmierung eingesetzt. Das Gemisch aus Druckluft und feinen Öltröpfchen wird in das Lager geblasen.  Stand: 01.12.2021  Seite 66 / 98
Nr. 0217	Wie können Gleitlager geschmiert werden? 	-Fettschmierung -Feststoﬀschmierung -Ölschmierung
Nr. 0218	Wie werden die Lager eingeteilt? 	Gleitlager und Wälzlager
Nr. 0219	Was für Wälzlager gibt es? 	-Rillenkugellager (ein- und zweireihig) -Schrägkugellager -Pendelkugellager -Axial Rillenkugellager -Zylinderrollenlager -Kegelrollenlager -Tonnenlager -Pendelrollenlager -Nadellager  8068.29240  8068.29243  Diese Lager gibt es in oﬀenen und geschlossenen Ausführungen.  Bild siehe Europa-Lehrmittel Fachkunde Metall Sachwortverzeichnis "Wälzlager"
Nr. 0220	Welche Vor- bzw. Nachteile besitzen Wälzlager gegenüber Gleitlagern? 	Vorteile: -Geringere Reibungsverluste und Wärmeentwicklung -Geringerer Schmierstoﬀverbrauch (manche Lager sind vom Hersteller auf Lebenszeit geschmiert) - Austauschbarkeit durch genormte Größen -Ausgleich von Wellenversatz und Wellendurchbiegung durch Einsatz von Pendellager  Nachteile: -Empﬁndlich gegen Schmutz- Stoßbelastungen und hohe Temperaturen -Größerer Einbaudurchmesser -Geringe Schwingungsdämpfung -Geringe Tragfähigkeit bei gleicher Baugröße  Stand: 01.12.2021  Seite 67 / 98
Nr. 0221	Welche Besonderheiten besitzen Nadellager? 	Nadellager sind Waelzlager mit besonders niedriger Bauform und werden haeuﬁg wegen ihres geringen Platzbedarfes verwendet. Die Bauart ist für relativ grosse Belastungen geeignet.
Nr. 0222	Was ist beim Ausbau von Wälzlagern zu beachten? 	-Zum Ausbau sind geeignete Abziehvorrichtungen zu verwenden. -Die Abziehkraft darf nicht über die Wälzkörper geführt werden.
Nr. 0223	Was ist beim Umgang mit Wälzlagern zu beachten? 	-Wälzlager sind sehr empﬁndlich gegen Verschmutzung und Korrosion. -Beim Einbau ist daher für größte Sauberkeit zu sorgen. -Die Lager sollten immer in der Originalverpackung aufbewahrt werden. -Das am Lager haftende Korrosionsschutzöl darf nicht abgewaschen werden.
Nr. 0224	Auf was muss beim Einbau eines Wälzlagers geachtet werden? 	Bei der Montage eines Wälzlagers muss vor allem darauf geachtet werden, dass die Einpresskraft nicht über die Wälzkörper übertragen wird. Es müssen immer Presshülsen und Montagehilfen in der richtigen Größe verwendet werden. Da bei größeren Wälzlagern die Einpresskräfte sehr hoch sein können, werden diese Lager im Ölbad oder mit Hilfe eines elektrischen Heizgerätes (induktiv) auf 80° - 100°C angewärmt und anschließend schnell und ohne verkanten auf den Wellenzapfen geschoben. Wenn bei großen Lagern ein fester Sitz am Außenring erforderlich ist, muss das Lagergehäuse angewärmt werden oder das Wälzlager auf -50°C gekühlt werden (Flüssigstickstoﬀ).
Nr. 0225	Welche Lager werden für eine Getriebewelle mit schrägverzahntem Zahnrad verwendet? 	Verwendung ﬁnden: Schrägkugellager, Kegelrollenlager, Axiales Pendelrollenlager
Nr. 0226	Als Lagerwerkstoﬀe für Gleitlager eignen sich: 	-Legierungen mit Kupfer (Bronze und Messing) -Zinn -Blei -Zink -Aluminiumbeschichtungen -Gusseisen -Sintermetalle und Kunststoﬀe
Nr. 0227	Was für Eigenschaften sollten Lagerwerkstoﬀe besitzen? 	-Hohe Verschleißfestigkeit -Gute Notlaufeigenschaften -Gute Benetzbarkeit durch den Schmierstoﬀ -Einbettungsfähigkeit für Abrieb -Wärmeleitfähigkeit zur Abfuhr von Reibungswärme -Korrosionsbeständigkeit -Schwingungsdämpfend
Nr. 0228	Welche Aufgaben haben Lager und Führungen? 	-Maschinenteile genau führen -Kräfte von dem bewegten auf das ruhende Maschinenteil mit geringem Reibungsverlust zu übertragen
Nr. 0229	Welche Reibungsarten werden unterschieden? 	-Gleitreibung -Rollreibung -Wälzreibung
Nr. 0230	Welche Arten von Wälzführungen gibt es? 	-Kugelbuchsen bei runden Führungsbahnen, Geradlinige und Drehbewegung möglich -Verdrehfeste Kugelführung, -Linearführung für lange Verschiebewege -Kugelgewindetrieb (CNC Werkzeugmaschinen)  Stand: 01.12.2021  Seite 69 / 98  Bild siehe Europa-Lehrmittel Fachkunde Metall Sachwortverzeichnis "Führungen"
Nr. 0231	Welche Eigenschaften soll eine Führung besitzen? 	-Geringe Reibung und niedriger Verschleiß -Hohe Führungsgenauigkeit durch geringes Spiel -Nachstellmöglichkeiten des Führungsspiels -Möglichst gute Dämpfungseigenschaften -Einfache Wartung und Schmiermöglichkeit -Abdichtungen gegen Schmutz und Späne
Nr. 0232	Welche Arten von Führungen gibt es? 	-Gleitführungen -Wälzführungen -Rollenführungen
Nr. 0233	Wie werden Führungen und Spindeln verschleißfest hergestellt? 	Durch Härten und Feinbearbeitung der Laufoberﬂächen, z.B. Flammhärten, Induktionshärten
Nr. 0234	Wo werden Gelenkwellen verwendet? 	Im Maschinenbau - sie dienen als Spindel- und Vorschubantrieb im Fahrzeugbau
Nr. 0235	Aus welchem Material werden Federn hergestellt? 	Sie werden aus Federstahl (z.B. 50 CrV 4), der durch Härten, Vergüten oder Kaltverformung seine Eigenschaften erhält, hergestellt.
Nr. 0236	Wozu werden Federn verwendet?  Stand: 01.12.2021  Seite 70 / 98  	-zum Auﬀangen von Stößen und Schwingungen -zum Aufeinanderpressen von Maschinenteilen -zur Speicherung von mechanischer Energie -zur Rückholung von Maschinenteilen
Nr. 0237	Nach welchen Belastungen werden Federn eingeteilt? 	-Zug -Druck -Biegung -Verdrehung (Torsion)
Nr. 0238	Welche Federarten gibt es? 	-Schraubenfeder -Schraubendrehfeder -Blattfeder -Drehstabfeder -Ringfeder -Tellerfeder -Gummifeder -Gasdruckfeder
Nr. 0239	Von welchen Faktoren ist die Federkraft bei Schraubenfedern abhängig? 	-Durchmesser des Federdrahtes -Wirkdurchmesser der Feder -Federweg und Windungszahl
Nr. 0240	Welche Vorteile bieten Tellerfedern?  8068.29310  8068.29313  8068.29314 	-Tellerfedern eignen sich für große Federkräfte bei kleinen Federwegen. -Je nach Zusammensetzung der einzelnen Federn zum Paket können Federweg und Federkraft variiert werden.
Nr. 0241	Was ist der Unterschied zwischen Wellen und Achsen?  Stand: 01.12.2021  8068.29315  Seite 71 / 98  	Achsen -dienen zum Tragen ruhender oder umlaufender Maschinenelemente -werden auf Biegung beansprucht und übertragen keine Drehmomente  Wellen -sind umlaufende Maschinenelemente, die Drehmomente übertragen -werden auf Verdrehung und Biegung beansprucht  Bild siehe Europa-Lehrmittel Fachkunde Metall Sachwortverzeichnis "Wellen" oder "Achsen"
Nr. 0242	Welche Arten von eingebauten Achsen und Wellen gibt es? 	Achsen für: Kranlaufräder, Seilrollen, Schienenfahrzeuge und Kraftfahrzeuge  Wellen für: Starre Wellen- Hohlwellen bei der Drehmaschine (Arbeitsspindel)- Kurbelwellen- GetriebewellenGelenkwellen (Kardanwelle, wird bei landwirtschaftlichen Maschinen viel verwendet) Biegsame Wellen (Handschleifgeräte, Antrieb von Tachometern)
Nr. 0243	Warum sind Achsen und Wellen meist abgesetzt? 	Durch Wellenabsätze (Zapfen) können andere Maschinenteile, wie Zahnräder oder Wälzlager leichter montiert und in axialer Richtung ﬁxiert werden.
Nr. 0244	Was sind Bolzen?  8068.29324 	Bolzen sind kurze Achsen, die Maschinenteile beweglich miteinander verbinden. z.B. Kolben und Pleuelstange oder die Glieder von Ketten.
Nr. 0245	Was ist bei der Herstellung eines Zapfens zu beachten? 	An den Übergängen von einem Durchmesser auf den anderen besteht durch die Kerbwirkung Dauerbruchgefahr / Eine zwecksmäßige Gestaltung des Überganges mit großen Radien oder genormten Freistichen vermindern die Kerbwirkung (Bruchgefahr).
Nr. 0246	Welche Aufgaben haben Dichtungen?  Stand: 01.12.2021  8068.29337  Seite 72 / 98  	Dichtungen sollen das Austreten oder Eindringen von Flüssigkeiten, Gasen oder festen Stoﬀen, wie z.B. Staub, an Trennstellen von Bauteilen verhindern oder verringern.
Nr. 0247	Wie können Dichtungen eingeteilt werden? 	-Ruhende Dichtungen (statisch) -Bewegungsdichtungen (dynamisch)
Nr. 0248	Nenne die meist verwendeten Dichtwerkstoﬀe! 	-Papier (Pappe) -Kunststoﬀe (z.B. PTFE – Teﬂon) -Graphit, -Metalle (z.B. Kupfer, Aluminium) -Dichtungspasten (z.B. Silikon) -Klebstoﬀe -Hanf -Gummi
Nr. 0249	Welche Bewegungsdichtungen gibt es? 	-Manschetten (Packungen) -Nutringe -Radial-Wellendichtringe -Axial-Gleitringdichtungen -Bewegungsdichtungen ohne Dichtwerkstoﬀ (Labyrinthdichtungen)  8068.29345  Bild siehe Europa-Lehrmittel Fachkunde Metall Sachwortverzeichnis "Dichtungen"
Nr. 0250	Welche Eigenschaften müssen Dichtwerkstoﬀe besitzen? 	-plastisch und elastisch formbar -chemisch beständig -temperatur- und alterungsbeständig -verschleißfest -geringe Reibungswiderstände aufweisend
Nr. 0251	Was sind ruhende Dichtungen? 	Bei den ruhenden Dichtungen muss der Dichtwerkstoﬀ sich den Unebenheiten der Dichtﬂächen anpassen. Zu den ruhenden Dichtungen zählen: Flachdichtungen, Proﬁldichtungen – Runddichtungen (O–Ringe), Flüssige Dichtungen, Schneidringe  Bild siehe Europa-Lehrmittel Fachkunde Metall Sachwortverzeichnis "Dichtungen"
Nr. 0252	Welche Anforderungen werden beim Einsatz schleifender Dichtungen an die Lauﬄächen gestellt? 	Die Oberﬂächen müssen, um den Verschleiß der Dichtung und des Bauteiles durch die Reibung gering zu halten, möglichst glatt und hart sein.
Nr. 0253	Wie werden Kupplungen eingeteilt? 	In schaltbare, nichtschaltbare und Kupplungen für Sonderzwecke.
Nr. 0254	Was für Aufgaben haben Kupplungen? 	-Form- oder kraftschlüssiges Verbinden von Wellen z.B. Motorwelle mit Getriebewelle -Unterbrechung oder Übertragung von Drehmomenten z.B. Kraftfahrzeugkupplung -Schalten von Getriebestufen z.B. bei Getrieben von Werkzeugmaschinen -Schutz vor Überlastung, z.B. im Kollisionsfall bei Maschinen (Abscherstift bei Drehmaschine) -Dämpfung von Stößen z.B. Kupplungen in Förderanlagen -Ausgleichen von Wellenversetzungen z.B. Gelenkkupplungen (Kardanwelle)
Nr. 0255	Welche schaltbaren Kupplungen gibt es? 	Formschlüssig sind: Klauenkupplungen, Zahnkupplungen  Kraftschlüssige sind: Einscheibenkupplung, Mehrscheibenkupplung, Lamellenkupplung, Kegelkupplung
Nr. 0256	Nenne Kupplungsbeispiele für Sonderzwecke!  Stand: 01.12.2021  Seite 74 / 98  	-Sicherheitskupplung (die einfachste Sicherheitskupplung ist der Abscherstift) -Sicherheitsrutschkupplung -Durchrastkupplung Anlaufkupplung -Fliehkraftkupplung -Freilaufkupplung
Nr. 0257	Wodurch unterscheiden sich form- und kraftschlüssige Kupplungen? 	-Formschlüssige Kupplungen sind nur im Stillstand schaltbar -Kraftschlüssige Kupplungen sind im Betrieb schaltbar
Nr. 0258	Wie funktionieren formschlüssige Schaltkupplungen? 	Bei diesen Kupplungen wird das Drehmoment durch ineinandergreifende Kupplungselemente übertragen.
Nr. 0259	Warum werden Sicherheitskupplungen verwendet? 	Um Maschinen und Geräte bei Überlast vor Schäden zu schützen (z.B. Kollision).
Nr. 0260	Wie funktionieren kraftschlüssige Schaltkupplungen? 	Bei kraftschlüssigen Schaltkupplungen erfolgt die Drehmomentübertragung durch Reibung.
Nr. 0261	Welche nichtschaltbaren Kupplungen gibt es? 	Starre Kupplungen: -Scheibenkupplung (Flanschkupplung) -Wellenkupplung mit Kegelhülse  Drehstarre Kupplungen: -Bogenzahnkupplung -Gelenkkupplung -Gelenkwelle  Stand: 01.12.2021  Seite 75 / 98  Elastische Kupplungen: -Metallfederkupplung -Gummihülsenkupplung
Nr. 0262	Wie können Riemen eingeteilt werden? 	In kraftschlüssige Riemen: -Flachriemen -Keilriemen -Rundriemen  In formschlüssige Riemen: -Zahnriemen
Nr. 0263	Auf welche Arten können Riemen gespannt werden? 	Die erforderliche Riemenvorspannung wird erreicht durch die richtige Riemenlänge, durch Vergrößerung des Achsenabstandes, indem der Antriebsmotor auf Spannschienen oder auf einer Wippe montiert wird oder durch Verwendung von Spannrollen. Die Spannrolle muss jeweils an der unbelasteten Seite (Leertrum), in der Nähe der kleinen Scheibe angebracht werden, um einen größeren Umschlingungswinkel zu erreichen.
Nr. 0264	Welche Vor- bzw. Nachteile eines Riementriebes gibt es? 	Vorteile: -Es können große Achsabstände überbrückt werden -elastische Kraftübertragung -geräusch- und schwingungsdämpfend -keine Schmierung notwendig  Nachteile: -Schlupf -hohe Lagerbelastung -großer Platzbedarf
Nr. 0265	Welche Keilriemenarten gibt es? 	-Normalkeilriemen -Schmalkeilriemen (ﬂankenoﬀen) -Mehrrippenkeilriemen -Breitkeilriemen  Stand: 01.12.2021  8068.29399  Seite 76 / 98  Bild siehe Europa Lehrmittel Fachkunde Metall Sachwortverzeichnis "Riementriebe"
Nr. 0266	Was ist beim Keilriementausch zu beachten? 	-Satzweise wechseln -korrekte Riemenspannung -kein Riemenscheibenversatz
Nr. 0267	Was sind die Vorteile eines Zahnriemens?  8068.29402 	Bei Zahnriemen erfolgt die Kraftübertragung nicht durch Reibung, sondern formschlüssig durch Ineinandergreifen der Zähne des Riemens und der Zahnriemenscheibe.  Zahnriemen verbinden die Vorteile des Flach- und des Keilriemen mit der Schlupﬀreiheit der Kette.  Da Zahnriemen eine geringere Riemenvorspannung haben müssen, ist die Lagerbelastung viel kleiner als bei Keilund Flachriemen.
Nr. 0268	Worauf ist bei der Fertigung einer Flachriemenscheibe zu achten? 	Ihre Lauﬄächen müssen glatt sein, um ein Riemenverschleiß durch den Schlupf möglichst gering zu halten. Außerdem ist die Lauﬄäche leicht gewölbt (konvex) ausgeführt, damit der Riemen zentriert läuft.
Nr. 0269	Wie funktioniert die Kraftübertragung beim Keilriemen? 	Sie erfolgt kraftschlüssig über die Seitenﬂächen des Keilriemens. Daher ist es wichtig, dass die Rillenﬂanken auf der Riemenscheibe eine glatte Oberﬂäche erhalten und die Rillen nach NORM gefertigt sind (32° – 38°).
Nr. 0270	Was gibt es für Kettenarten? 	-Rollen- und Buchsenketten -Mehrfachrollenketten -Bolzenketten -Gallketten  Stand: 01.12.2021  8068.29411  Seite 77 / 98  -Fleyerketten -Zahnketten (Sonderform)  Bild siehe Europa-Lehrmittel Fachkunde Metall Sachwortverzeichnis "Ketten"
Nr. 0271	Was sind die Vorteile und Nachteile eines Kettentriebes? 	Vorteile: -Übertragung von großen Kräften/ Drehmomenten -formschlüssig (schlupﬀrei) -kaum empﬁndlich gegen Feuchtigkeit- Schmutz und hohe Temperaturen -Einbauerleichterung durch Kettenschloss  Nachteile: -hohe Laufgeräusche -wartungsintensiv -Kettenspannung und Schmierung -Kettengeschwindigkeit begrenzt
Nr. 0272	Welche Zahnradarten gibt es? 	-Stirnräder -Kegelräder -Schraubenräder -Schneckenrad und Schnecke -Zahnstange  Bild siehe Europa-Lehrmittel Fachkunde Metall Sachwortverzeichnis "Zahnräder"
Nr. 0273	Welche Stirnräderarten gibt es? 	Es gibt Stirnräder mit: -Außen- und Innenverzahnung -Geradverzahnung -Schrägverzahnung -Pfeilverzahnung  8068.29419  8068.29422  Bild siehe Europa-Lehrmittel Fachkunde Metall Sachwortverzeichnis "Zahnräder"
Nr. 0274	Wo werden Schneckenräder eingesetzt?  Stand: 01.12.2021  Seite 78 / 98  	Sie werden überall dort eingesetzt, wo sich zwei Wellen unter einem Winkel von 90° kreuzen und wo große Übersetzungsverhältnisse gefordert sind (Teilapparat). Sie sind selbsthemmend.  Bild siehe Europa-Lehrmittel Fachkunde Metall Sachwortverzeichnis "Schneckenräder"
Nr. 0275	Welche Aufgaben erfüllen Zahnräder? 	Zahnräder übertragen Drehbewegungen formschlüssig von einer Welle auf eine andere. Dabei greifen die Zähne des Antriebs-und des Abtriebsrades ineinander. Durch Wahl der Zähnezahl und damit des Übersetzungsverhältnisses erhält man die gewünschte Drehzahl, Drehrichtung und Drehmoment an der Antriebswelle.
Nr. 0276	Wo werden Schraubenräder eingesetzt? 	Schraubenräder dienen zur Drehmomentübertragung zwischen zwei sich unter einem beliebigen Winkel kreuzenden Wellen. Sie können nur geringe Drehmomente übertragen, da sich die Zahnﬂanken nur an einem Punkt berühren.
Nr. 0277	Welche Verzahnungsarten gibt es? 	Zykloidenverzahnung: nur bei Präzisionsverzahnungen (Uhrwerk)  Evolventenverzahnung: Maschinen- und Kraftfahrzeugbau
Nr. 0278	Wie können Zahnräder hergestellt werden? 	Zahnräder Herstellung: Spanende Fertigung: Wälzfräsen- Wälzstoßen- Proﬁlfräsen- Wälzschleifen- Erodieren Spanlose Fertigung: Spritzgießverfahren- Sinterverfahren- Formpressen- Schmieden
Nr. 0279	Welche Zahnradmaße sind zur Fertigung notwendig? 	Sind Modul, Zähnezahl und Kopfspiel eines Zahnrades bekannt, können alle anderen Maße berechnet oder aus  Stand: 01.12.2021  Seite 79 / 98  Tabellen entnommen werden.
Nr. 0280	Wo werden Kegelräder eingesetzt?  8068.29430 	Kegelräder können bei sich kreuzenden Wellen Drehmomente übertragen. Die Wellen schneiden sich in einem Punkt.
Nr. 0281	Welche Vor- bzw. Nachteile hat die Schrägverzahnung? 	Vorteil: -Bei Stirnrädern mit Schrägverzahnung sind immer mehrere Zähne gleichzeitig im Eingriﬀ -Ihr Lauf wird ruhiger und höhere Drehmomente werden übertragen  Nachteil: -Sie erzeugen Axialkräfte, die von den Getriebelagern aufgenommen werden müssen
Nr. 0282	Welches Ziel wird durch eine stufenweise Automatisierung angestrebt? 	-Erhöhung der Maschinennutzung -Entlastung des Bedienpersonals -Menschliche Störeinﬂüsse minimieren -Nebenzeiten verringern
Nr. 0283	Womit können geradlinige Bewegungen ausgeführt werden? 	Umwandlung der Drehbewegung eines Elektromotors in eine geradlinige Bewegung durch Gewindespindel mit: -Mutter -Zahnstangengetriebe -Riemen oder Ketten -pneumatische oder hydraulische Zylinder -Linearmotoren
Nr. 0284	Nenne einige Antriebsbeispiele für geradlinige Bewegungen! 	Trapezgewinde bei Drehmaschinen (Leitspindel – Schlossmutter)  Stand: 01.12.2021  Seite 80 / 98  Schraubstöcke  Kugelgewindetrieb an Werkzeugmaschinen für Vorschübe  Schneckentriebe bei Förderbändern –Umsetzung durch Riemen und Ketten -Hydraulikzylinder bei Flächenschleifmaschine  Linearmotoren erzeugen direkt eine geradlinige Bewegung
Nr. 0285	Welche Formen von Gleitführungen gibt es? 	Flachführungen -einfach herzustellen - benötigen eine Nachstellleiste zum Einstellen des Führungsspiels bei bestimmten Anwendungen sowie eine Schließleiste, die das Abheben des Schlittens verhindert  V-Führungen -können auch kleine Querkräfte aufnehmen -bei Abnutzung stellen sie sich selbständig nach -werden oft mit Flachführungen kombiniert (z.B. Spitzendrehmaschine- Reitstock).  Schwalbenschwanzführungen -verhindern durch ihre Form ein Abheben des Tisches -mit einer Nachstellleiste kann das Spiel eingestellt werden  Rundführungen -sind einfach und genau herzustellen -lassen sich allerdings bei zunehmendem Verschleiß nur sehr schwer nachstellen  Bilder siehe Europa-Lehrmittel Fachkunde Metall Sachwortverzeichnis "Führungen"
Nr. 0286	Welche Vorteile bieten stufenlose Getriebe? 	Mit stufenlosen Getrieben können die Abtriebsdrehzahlen bei konstanter Antriebsdrehzahl stufenlos zwischen der kleinsten und der größten Drehzahl eingestellt werden.
Nr. 0287	Welche Vorteile bietet das Schneckenradgetriebe? 	-geringer Platzbedarf im Verhältnis zur Übersetzungszahl -wirkt in einer Richtung selbsthemmend -es wirken große Kräfte  Stand: 01.12.2021  Seite 81 / 98
Nr. 0288	Welche stufenlosen Getriebe gibt es? 	-Zugmittelgetriebe -Breitkeilriemengetriebe -Lamellenkettengetriebe -Rollenkettengetriebe -Reibradgetriebe
Nr. 0289	Wie funktioniert das Zugmittelgetriebe?  8068.29466 	Das Antriebsscheibenpaar wird verstellt und durch den Zug des Riemens wird das Abtriebsscheibenpaar auseinandergedrückt.  Durch unterschiedlichen Einstellungen ändern sich die Laufdurchmesser so, dass sowohl Übersetzung ins Schnelle als auch ins Langsame entstehen.  Bild siehe Europa-Lehrmittel Fachkunde Metall Sachwortverzeichnis "Zugmittelgetriebe"
Nr. 0290	Welches sind die wichtigsten schaltbaren Getriebe? 	Schieberadgetriebe und Kupplungsgetriebe
Nr. 0291	Was sagt das Übersetzungsverhältnis 20 : 1 aus? 	Während die treibende Welle 20 Umdrehungen dreht, dreht sich die getriebene Welle einmal.
Nr. 0292	Welche Leistungsmerkmale von Industrierobotern ergeben sich aus der Bauart? 	-Anzahl der Bewegungsachsen (höchster Freiheitsgrad, min. 6 Achsen) -Nennlast -Positioniergenauigkeit -Wiederholungsgenauigkeit -Geschwindigkeit -Arbeits- bzw. Bewegungsraum  Stand: 01.12.2021  Seite 82 / 98
Nr. 0293	Welche Instandhaltungskonzepte werden unterschieden? 	-Intervallabhängige Instandhaltung -Zustandsabhängige Instandhaltung -Störungsbedingte Instandhaltung
Nr. 0294	Welche Teilbereiche umfasst die Instandhaltung von Maschinen und Anlagen? 	-Wartung -Reinigen, Schmieren, Nachstellen Inspektion -Messen, Prüfen, Diagnostizieren Instandsetzung -Ausbessern, Reparieren, Austauschen Verbesserung -Auswerten, Nachjustieren, Prüfen
Nr. 0295	Was ist der Wirkungsgrad einer Maschine? 	Das Verhältnis der technisch nutzbaren Leistung zur zugeführten Leistung, wird als Wirkungsgrad bezeichnet (Leistungsverlust durch Reibungswärme).  Thema: Längenprüftechnik
Nr. 0296	Wodurch unterscheiden sich Messen und Lehren bei objektiven Prüfungen? 	Messen: Ist das Vergleichen z. B. einer Länge oder eines Winkels mit dem Messergebnis eines Messgerätes. Das Ergebnis ist ein Messwert.  Lehren: Ist das Vergleichen des Prüfgegenstandes mit einer Lehre. Das Ergebnis gibt auskunft, ob der Prüfgegenstand in der geforderten Toleranz ist, oder nicht.  Stand: 01.12.2021  Seite 83 / 98  Fachkunde Metall, 57. Auﬂage, Verlag Europa-Lehrmittel
Nr. 0297	Welche Lehrenarten werden unterschieden? 	-Maßlehren -Formlehren -Grenzlehren  Fachkunde Metall, 57. Auﬂage, Verlag Europa-Lehrmittel
Nr. 0298	Wofür werden Messuhren verwendet? 	-Für Längenmessungen.  Stand: 01.12.2021  Seite 84 / 98  -Zum Messen von Vertiefungen. -Zum Prüfen von Ebenheit, Parallelität und Rundlauf. -Für Einstellungsarbeiten an Maschinen.  Fachkunde Metall, 57. Auﬂage, Verlag Europa-Lehrmittel
Nr. 0299	Wofür werden Fühlhebelmessgeräte verwendet? 	Für Messungen von Rund-, Plan- und Ebenheit, sowie zum Ausrichten von Bauteilen.  Fachkunde Metall, 57. Auﬂage, Verlag Europa-Lehrmittel
Nr. 0300	Welche Aufgabe haben Oberﬂächenzeichen in einer technischen Zeichnung? 	Die Kennzeichnung der geforderten Oberﬂächenbeschaﬀenheit. Neben der Maßhaltigkeit und Werkstoﬀqualität eines Bauteiles kann für spezielle Anwendungsbereiche auch das Aussehen oder die Oberﬂächengüte von Bedeutung sein (Gleitﬂächen usw.).
Nr. 0301	Warum werden in der Technik Toleranzen verwendet?  Stand: 01.12.2021  8068.29589  Seite 85 / 98  	Besonders in der Serienfertigung müssen Werkstücke, unabhängig von ihren Herstellern, ohne Nacharbeit montiert werden und untereinander austauschbar sein können.
Nr. 0302	In welche Toleranzklassen werden die Allgemeintoleranzen eingeteilt? 	-Fein -Mittel -Grob -Sehr grob
Nr. 0303	Was bedeuten die Begriﬀe "Spielpassung", "Übergangspassung" und "Übermaßpassung"? 	Spielpassung: Das Mindestmaß der Bohrung ist größer als das Höchstmaß der Welle  Übergangspassung: Es kann sowohl das Übermaß als auch Spiel auftreten  Übermaßpassung: Das Höchstmaß der Bohrung ist kleiner als das Mindestmaß der Welle  8068.29597  Fachkunde Metall, 57. Auﬂage, Verlag Europa-Lehrmittel
Nr. 0304	Was bedeutet "Passungssystem Einheitsbohrung"? 	Bohrungen werden nach dem Toleranzfeld H gefertigt (das Grundabmaß ist gleich Null).
Nr. 0305	Was bedeutet Ø 20 H7?  Stand: 01.12.2021  8068.29600  Seite 86 / 98  	Nennmaß 20 mm Durchmesser Grundabmaß H (Lage des Toleranzfeldes zur Nulllinie) Toleranzgrad 7 (je größer die Zahl, umso größer die Toleranz)  Fachkunde Metall, 57. Auﬂage, Verlag Europa-Lehrmittel
Nr. 0306	Beschreibe die gebräuchlichsten Form- und Lagetoleranzen nach ihrem Symbol und ihrer Bedeutung! 	Als Beispiel:  siehe Toleranzarten im Europa-Lehrmittel Fachkunde Metall
Nr. 0307	Womit können Gewinde geprüft werden? 	-Gewindekämme -Messschieber -Gewindemessgeräten mit Feinzeigern -Koordinatenmessgeräten -Gewindemessschrauben -Messmikroskopen -Proﬁlprojektoren -Gewindelehren  3 Beispiele:  Stand: 01.12.2021  Seite 87 / 98  Fachkunde Metall. 57. Auﬂage, Verlag Europa-Lehrmittel
Nr. 0308	Nach welchen 2 Arten von Qualitätsmerkmalen wird unterschieden? 	 Fachkunde Metall, 57. Auﬂage, Verlag Europa-Lehrmittel
Nr. 0309	Was bedeutet der Begriﬀ "Qualität"? 	Die Beschaﬀenheit eines Produktes bezüglich der Eignung, festgelegte Forderungen und erwartete Eigenschaften zu erfüllen.  Thema: Fügen und Trennen - Schweißtechnik
Nr. 0310	Erkläre den Begriﬀ "Schweißen"!  Stand: 01.12.2021  Seite 88 / 98  	Schweißen (thermisches Fügen) ist das Vereinigen oder Beschichten von Werkstoﬀen in ﬂüssigem oder plastischem Zustand unter Anwendung von Wärme und/oder Kraft, ohne oder mit Zusatzwerkstoﬀen.
Nr. 0311	Welche Vor- bzw. Nachteile hat das Schweißen gegenüber anderen Fügeverfahren? 	Vorteile: Freie Gestaltung durch einfache Ausführung Gewichtseinsparung Hochfeste und dichte Verbindung Günstiger Kraftlinienverlauf Zeitersparnis  Nachteile: Gefügeänderungen in der Wärmeeinﬂusszone Verzug und Schrumpfung am Bauteil Spannungen im Bauteil Nicht alle Metalle sind zum Schweißen geeignet
Nr. 0312	Welche Schweißnahtformen gibt es? 	 Fachkunde Metall, 56. Auﬂage, Verlag Europa-Lehrmittel weitere Nahtformen: Ecknaht Überlappnaht
Nr. 0313	Was bedeutet der Begriﬀ "a" Maß beim Schweißen? 	Ist das Maß für die Schweißnahtdicke bei Kehlnähten.
Nr. 0314	Was gehört zu einer Gasschmelzschweißanlage? 	 Fachkunde Metall, 56. Auﬂage, Verlag Europa-Lehrmittel
Nr. 0315	Welche Kennzeichen hat eine Sauerstoﬀﬂasche? 	Weiße Flaschenschulter, die Flaschenfarbe selbst ist nicht genormt und kann blau, grau oder weiß sein. Der Anschluss für den Druckminderer ist ein ¾" (Zoll) Rechtsgewinde-Anschluss. Der Schriftzug „Sauerstoﬀ“ ist in die Flasche eingeschlagen.
Nr. 0316	Wie ist ein Druckminderer aufgebaut und welche Aufgabe hat er? 	 Stand: 01.12.2021  Seite 90 / 98  Fachkunde Metall, 56. Auﬂage, Verlag Europa-Lehrmittel Durch den Druckminderer wird der hohe Flaschendruck auf den erforderlichen Arbeitsdruck reduziert (beim Schweißen Acetylen auf 0,25 bis 0,5 bar und Sauerstoﬀ auf 2,5 bis 3,5 bar).
Nr. 0317	Was ist bezüglich Unfallverhütung bei Gasﬂaschen zu beachten? 	Sauerstoﬀﬂaschen sind frei von Öl und Fett zu halten, da Sauerstoﬀ mit Öl und Fett explosionsartig reagiert. Gasﬂaschen dürfen nur mit aufgeschraubter Schutzkappe transportiert werden. Gasﬂaschen sind gegen Umfallen zu sichern und vor Stoß, Erwärmung (z.B. durch Sonnenbestrahlung und Heizung) sowie vor Frost zu schützen. Acetylenﬂaschen müssen bei der Gasentnahme senkrecht stehen oder so gelagert werden, dass das Flaschenventil mindestens 40 cm höher liegt als der Flaschenfuß, damit kein Aceton auslaufen kann.
Nr. 0318	Wie werden die Schweißverfahren unterteilt? 	 Stand: 01.12.2021  Seite 91 / 98  Bertsch Energy
Nr. 0319	Welche persönliche Schutzausrüstung ist beim Lichtbogenhandschweißen zu tragen? 	Schwer entﬂammbare Arbeitskleidung. Sicherheitsschuhe. Lederschürze oder Lederjacke. Lederhandschuhe. Schweißschild mit Schutzgläsern der richtigen Schutzstufe. Kopfschutz.
Nr. 0320	Wie werden die Schutzgasschweißverfahren unterteilt? 	In Wolfram-Schutzgasschweißen: WP (Wolfram-Plasmaschweißen) 15 WIG (Wolfram-Inert-Gasschweißen) 141  In Metall-Schutzgasschweißen: MIG (Metall-Inert-Gasschweißen) 131 MAG (Metall-Aktiv-Gasschweißen) 135
Nr. 0321	Wie funktioniert das WIG-Schweißen? 	 Stand: 01.12.2021  Seite 92 / 98  Fachkunde Metall, 56. Auﬂage, Verlag Europa-Lehrmittel Als Stromquellen kommen Gleich- oder Wechselstrommaschinen zum Einsatz. Lichtbogenträger ist eine nicht abschmelzende Wolfram-Elektrode. Als Schutzgase kommen Argon, Helium oder Argon/Helium Gemische zur Anwendung. Das WIG-Schweißen wird bei unlegierten, legierten Stählen, sowie bei allen NE–Metallen angewendet.
Nr. 0322	Welche Schutzstufen gibt es bei den Schweißgläsern? 	Normgläser gibt es von Schutzstufe 9 bis 14. Schweißerschutzbrillen gibt es von Schutzstufe 1,7 bis 6.
Nr. 0323	Welches Gasgemisch wird beim MAG-Schweißen am häuﬁgsten verwendet? 	Beim MAG-Schweißen kommt am häuﬁgsten die Mischung 82% Argon und 18% CO² zur Anwendung.
Nr. 0324	Welche thermische Trennverfahren gibt es? 	Das autogenes Brennschneiden. Das Plasma-Schmelzschneiden. Das Laserstrahlschneiden. Bei den hier angeführten Verfahren ist das "Werkzeug" ein Gasstrahl (Schneidstrahl).
Nr. 0325	Was ist bei der Handhabung eines Winkelschleifers zu beachten? 	Den Winkelschleifer nur mit Scheibenschutz in Betrieb nehmen. Beim Schleifscheibenwechsel immer Netzstecker ziehen. Schutzbrille bzw. Schutzschild und Gehörschutz verwenden. Maximale Drehzahl und Verfallsdatum der Schleifscheibe beachten. Ausreichender Schnittdruck bewirkt rechtzeitiges Ausbrechen des Schleifkornes. Bei Arbeiten mit Trennscheiben ist besondere Vorsicht geboten. Gefahr des Verkantens und möglicher Bruch der Trennscheibe.
Nr. 0326	Durch welche Maßnahmen kann dem Verzug durch Schweißen an Bauteilen vorgebeugt werden? 	Durch Vorspannung. Durch Vorwärmen. Durch die richtige Schweißfolge (Pilgerschrittverfahren). Durch die richtige Schweißgeschwindigkeit (Wärmeeinbringung).
Nr. 0327	Welche allgemeinen Sicherheitsvorkehrungen sind beim Schweißen zu beachten? 	Für jedes Schweiß- und Trennverfahren sind die richtigen Schutzschilder bzw. die richtigen Schutzbrillen, mit Schutzgläsern der richtigen Schutzstufe zu verwenden. Der Schweißbereich muss ausreichend abgeschirmt sein, um auch andere Personen vor Strahlen und Spritzern zu schützen. Der Arbeitsplatz muss gut belüftet sein, beziehungsweise es muss eine Absaugung eingesetzt werden. Bei Schweißarbeiten bzw. Schneidarbeiten ist darauf zu achten, dass keine brennbaren Gegenstände in der Nähe sind, die durch herunterfallendes Schweißgut und Spritzer in Brand geraten könnten. In engen Räumen oder Kesseln darf reiner Sauerstoﬀ NIEMALS zum Belüften verwendet werden (Brandgefahr der Kleider)! Sauerstoﬀ reagiert mit Ölen und Fetten explosionsartig. Die eigene Vorsicht ist der beste Unfallschutz!  Thema: Werkzeug - Stanztechnik
Nr. 0328	Was bedeutet der Begriﬀ „Umformen“? 	Umformen ist ein Fertigungsverfahren, das an einem festen Körper eine bleibende Formänderung herbeiführt. Die Benennung der Werkzeuge erfolgt meist durch die Angabe des Fertigungsverfahrens, z.B. Biegewerkzeug.
Nr. 0329	Was geschieht mit dem Werkstoﬀ bei der Umformtechnik? 	Beim Umformen wird der Werkstoﬀ in eine andere geometrische Form gebracht. Der „Faserverlauf“ bleibt erhalten, die Festigkeit wird verbessert und es können auch schwierige Formen mit guter Oberﬂächenqualität und engen Toleranzen hergestellt werden.
Nr. 0330	Was bedeutet der Begriﬀ „Biegeumformen“? 	Beim Biegeumformen können Bleche, Rohre und andere Halbzeuge spanlos umgeformt werden.  Quelle: Metalltechnik, Der Werkzeugbau, 16 Auﬂage Verlag Europalehrmittel  Quelle: Metalltechnik, Der Werkzeugbau, 16 Auﬂage Verlag Europalehrmittel
Nr. 0331	Aus welchen Teilen besteht ein Biegewerkzeug? 	Die einfachste Art besteht aus dem Biegestempel, der Teileaufnahme und dem Biegegesenk.  Thema: Umweltschutz
Nr. 0332	Welche umwelttechnischen Vorteile bietet ein eﬃzientes Energiemanagement? 	Energie zu sparen ist gleichbedeutend mit nachhaltigem Ressourcenmanagement und schont so die Umwelt. Energiegewinnung ist meist mit der Emission von Schadstoﬀen verbunden (Energiegewinnung durch fossile Brennstoﬀe, AKW, usw.).  Stand: 01.12.2021  Seite 95 / 98
Nr. 0333	Wie soll die Auswahl der Werk- und Hilfsstoﬀe aus Sicht des Umweltschutzes erfolgen? 	Es dürfen nur Werk- und Hilfsstoﬀe eingesetzt werden, die nicht gesundheitsschädlich und ohne Schädigung der Umwelt zu erzeugen, zu verarbeiten und zu entsorgen sind. Sie sind so auszuwählen, dass sie möglichst wiederverwendbar sind.
Nr. 0334	Welche Vorteile bietet eﬃzientes Recycling? 	Recycling schont Ressourcen und spart Energie, da bei der Neugewinnung von Rohstoﬀen sehr viel Energie benötigt wird (z.B. Alu) und dementsprechend auch Schadstoﬀe emittiert werden. Reycling spart Geld!
Nr. 0335	Was ist Recycling?  8068.29964 	Abfall (bzw. Wertstoﬀe) wird getrennt, sauber und sortenrein gesammelt und als Sekundärstoﬀ wieder verwertet (z.B. Papier, Metall, Glas, Kunststoﬀe ...).
Nr. 0336	Wie erfolgt die Entsorgung von Abfällen und Gefahrenstoﬀen? 	Gebrauchte Gefahrenstoﬀe und umweltbelastende Abfälle aus der Fertigung müssen getrennt, gesammelt und in gekennzeichneten Behältern der Entsorgung zugeführt werden.
Nr. 0337	Was kann gegen die Gesundheitsgefährdung durch Kühlschmierstoﬀe unternommen werden? 	-Maschinenkapselung -Ölabsaugung -Anwendung von speziellen Hautcremen -Tragen geeigneter Schutzausrüstung (mindestens Handschuhe und Brille)  Thema: Sicherheitsvorschriften, Schutzmaßnahmen, Unfallverhütung
Nr. 0338	Was ist bei der Benutzung von elektrischen Betriebsmitteln zu beachten?  Stand: 01.12.2021  Seite 96 / 98  	Die Anschlussleitungen der Maschine dürfen nicht beschädigt sein (Zuleitungskabel, Stecker von Bohrmaschinen, Winkelschleifern usw.). Erkennbare Mängel an Maschinen müssen sofort dem Vorgesetzten gemeldet werden.
Nr. 0339	Welche Maßnahmen sind bei Erkennen von Gefahren zu treﬀen? 	-Mängel an Maschine und Werkzeug sowie Arbeitsgerät muss sofort gemeldet werden -Scharfe, spitzige Werkzeuge nicht in der Arbeitskleidung tragen -Arbeitskleidung muss eng anliegen und darf nicht zerrissen sein -Sicherheitsschuhe tragen -Kein Tragen von Schmuck, Uhren bzw. Ringe -Schutzeinrichtungen (Abschrankungen), Hinweisschilder und Sicherheitseinrichtungen (NOT AUS-Schalter) müssen vorhanden sein -Drehende Räder, Spindeln und Wellen müssen abgeschirmt sein -Kennzeichnungspﬂicht von brennbaren, explosiven und ätzenden Stoﬀen, sicherer Aufbewahrungsort WICHTIG: Fluchtwege müssen stets freigehalten sein!
Nr. 0340	Wodurch werden Gefahren beim Arbeiten an Hydraulik- und Pneumatikanlagen verhindert? 	Durch Beachten von: -Sicherheitsvorschriften des Herstellers einhalten -Sichtkontrolle der Hydraulikleitungen auf Undichtheit -System drucklos
Nr. 0341	Welche Gruppen von Sicherheitszeichen gibt es? 	Verbotszeichen -rund -zeigen die verbotene Handlung als schwarzes Bild auf weißem Grund -erkennbar durch roten Rand mit roten Querbalken  Warnzeichen -dreieckig mit nach oben zeigender Spitze -Farben gelb mit schwarz  Gebotszeichen -kreisförmig -die Farben blau mit weiß zeigen die gebotenen Schutzmaßnahmen -sie schreiben bestimmte Verhaltensweisen zwingend vor  Rettungszeichen -quadratisch oder rechteckig -Farben grün mit weiß  Stand: 01.12.2021  Seite 97 / 98  Brandschutzzeichen -quadratisch -Farben rot mit weiß  Bild siehe Europa-Lehrmittel Fachkunde Metall
Nr. 0342	Wodurch werden Unfälle verursacht? 	Menschliches Versagen: Lässt sich trotz Schulung nie ganz ausschließen. Kann aber durch gewissenhafte Kontrolle, Anbringen von Sicherheitseinrichtungen reduziert werden, z.B. Abschrankung, Sicherheitsschalter.  Technisches Versagen: Werkstoﬀermüdung, unvorhergesehene Überlastung, Ausfall von Sicherheitsschaltern, Spanndruck  Stand: 01.12.2021  Seite 98 / 98''';
